<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		util
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-01-02
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php if ($this->latitude && $this->longitude) : ?>
<div class="utilWidgetsGoogleMap">
<?php if ($this->ajax) : ?>
	<?php echo $this->translator()->_('show.unpreviewableInAjaxMode'); ?>		
<?php else : ?>
	
	<div id="utilWidgetsGoogleMap_<?php echo $this->uid; ?>" style="width: 100%; height: 300px"></div>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
	<script type="text/javascript">
	dojo.addOnLoad(function() {
		var latlng = new google.maps.LatLng(<?php echo $this->latitude; ?>, <?php echo $this->longitude; ?>);
		var map	   = new google.maps.Map(document.getElementById("utilWidgetsGoogleMap_<?php echo $this->uid; ?>"), {
			zoom: <?php echo $this->zoom; ?>,
			center: latlng,
			mapTypeId: google.maps.MapTypeId.ROADMAP,
			streetViewControl: false,
			mapTypeControl: false
		});
		var marker = new google.maps.Marker({
			position: latlng,
			map: map
	    });
	});
	</script>
	
<?php endif; ?>
</div>
<?php endif; ?>
