<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		tag
 * @subpackage	hooks
 * @since		1.0
 * @version		2012-03-10
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false">
	<!-- Banners -->
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', splitter: false, style: 'padding: 8px'">
		<div class="tagHooksTagProviderTagsContainer" data-dojo-type="dojo.dnd.AutoSource" data-dojo-props="accept: [], selfAccept: false, selfCopy: false">
			<?php if (!$this->tags || count($this->tags) == 0) : ?>
			<?php echo $this->translator()->_('show.notFound'); ?>
			<?php else : ?>
			
			<?php foreach ($this->tags as $tag) : ?>
			<div id="tagHooksTagProviderItem_<?php echo $tag->tag_id; ?>" class="tagHooksTagProviderTagItem dojoDndItem" dndtype="tagTagItemDnd"
				data-app-entity-props="<?php echo $this->encoder()->encode($tag); ?>">
				<?php echo $tag->title; ?>
			</div>
			<?php endforeach; ?>
			
			<?php endif; ?>
		</div>
	</div>
	<!-- /Banners -->
	
	<!-- Paginator -->
	<?php if ($this->paginator->count() > 1) : ?>
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'padding: -8px'">
	<?php echo $this->paginator('slidingToolbar')->render($this->paginator, "javascript: dojo.publish('/app/tag/hooks/tagprovider/search/onGotoPage', [__PAGE__]);"); ?>
	</div>
	<?php endif; ?>
	<!-- /Paginator -->
</div>

<script type="text/javascript">
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojo.dnd.Source");
</script>
