<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('photo.edit.title'));
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/media/css/admin/default/styles.css");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/layout/resources/ResizeHandle.css");
</script>

<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false" style="height: 100%; width: 100%">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false" style="margin: -8px">
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appSaveIcon'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/media/photo/edit/onSave");
			</script>
		</button>
		
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appCancelIcon'">
			<?php echo $this->translator()->_('global._share.closeAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/media/photo/edit/onClose");
			</script>
		</button>
		
		<div data-dojo-type="dijit.ToolbarSeparator"></div>
		
		<!-- UndoRedo -->
		<button id="mediaPhotoEditUndoButton" type="button" disabled="disabled">
			<?php echo $this->translator()->_('global._share.undoAction'); ?>
		</button>
		
		<button id="mediaPhotoEditRedoButton" type="button" disabled="disabled">
			<?php echo $this->translator()->_('global._share.redoAction'); ?>
		</button>
		<!-- /UndoRedo -->
		
		<!-- ResizeDialog -->
		<div data-dojo-type="dijit.form.DropDownButton" data-dojo-props="showLabel: false, iconClass: 'appIcon mediaPhotoResizeIcon'">
			<span><?php echo $this->translator()->_('photo.edit.resizeAction'); ?></span>
			<div id="mediaPhotoEditResizeDialog" data-dojo-type="dijit.TooltipDialog" data-dojo-props="style: 'width: 250px', class: 'appForm'">
				<div class="appFormRow">
					<label for="by" style="width: 50px"><?php echo $this->translator()->_('photo.edit.resizeBy'); ?>:</label>
					<div data-dojo-type="dijit.form.RadioButton" data-dojo-props="type: 'radio', name: 'resizeBy', value: 'percentage', checked: true">
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						dojo.publish("/app/media/photo/edit/onSetResizeBy", [ "percentage" ]);
						</script>
					</div>
					<?php echo $this->translator()->_('photo.edit.resizeByPercentage'); ?>
					
					<div data-dojo-type="dijit.form.RadioButton" data-dojo-props="type: 'radio', name: 'resizeBy', value: 'pixels'">
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						dojo.publish("/app/media/photo/edit/onSetResizeBy", [ "pixels" ]);
						</script>
					</div>
					<?php echo $this->translator()->_('photo.edit.resizeByPixels'); ?>
				</div>
			
				<div class="appFormRow">
					<label for="width" style="width: 50px"><?php echo $this->translator()->_('photo._share.width'); ?>:</label>
					<div id="mediaPhotoEditResizeWidth" data-dojo-type="dijit.form.TextBox" data-dojo-props="value: 100, intermediateChanges: true, style: 'width: 50px'">
						<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="value">
						dojo.publish("/app/media/photo/edit/onSetResizeWidth", [ value ]);
						</script>
					</div>
				</div>
				
				<div class="appFormRow">
					<label for="width" style="width: 50px"><?php echo $this->translator()->_('photo._share.height'); ?>:</label>
					<div id="mediaPhotoEditResizeHeight" data-dojo-type="dijit.form.TextBox" data-dojo-props="value: 100, intermediateChanges: true, style: 'width: 50px'">
						<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="value">
						dojo.publish("/app/media/photo/edit/onSetResizeHeight", [ value ]);
						</script>
					</div>
				</div>
				
				<div class="appFormRow">
					<label style="width: 50px">&nbsp;</label>
					<div data-dojo-type="dijit.form.CheckBox" data-dojo-props="type: 'checkBox', checked: true">
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="value">
						dojo.publish("/app/media/photo/edit/onSetMaintainRatio", [ value ]);
						</script>
					</div>
					<?php echo $this->translator()->_('photo.edit.maintainAspectRatio'); ?>
				</div>
				
				<hr class="appSeparator" />
				
				<div class="appFormRow">
					<label style="width: 50px">&nbsp;</label>
					<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
						<?php echo $this->translator()->_('photo.edit.resizeAction'); ?>
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						dojo.publish("/app/media/photo/edit/onResize");
						</script>
					</button>
					
					<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
						<?php echo $this->translator()->_('global._share.cancelAction'); ?>
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						dojo.style("mediaPhotoEditResizeDialog", "display", "none");
						</script>
					</button>
				</div>
			</div>
		</div>
		<!-- /ResizeDialog -->
		
		<!-- RotateAndFlip -->
		<div data-dojo-type="dijit.form.DropDownButton" data-dojo-props="showLabel: false, iconClass: 'appIcon mediaPhotoRotateLeftIcon'">
			<span><?php echo $this->translator()->_('photo.edit.rotateAction'); ?></span>
			
			<div data-dojo-type="dijit.Menu" style="display: none">
				<div data-dojo-type="dijit.MenuItem" data-dojo-props="iconClass: 'appIcon mediaPhotoRotateLeftIcon'">
					<?php echo $this->translator()->_('photo.edit.rotateLeftAction'); ?>
					<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
					dojo.publish("/app/media/photo/edit/onRotate", [ 90 ]);
					</script>
				</div>
				
				<div data-dojo-type="dijit.MenuItem" data-dojo-props="iconClass: 'appIcon mediaPhotoRotateRightIcon'">
					<?php echo $this->translator()->_('photo.edit.rotateRightAction'); ?>
					<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
					dojo.publish("/app/media/photo/edit/onRotate", [ -90 ]);
					</script>
				</div>
				
				<div data-dojo-type="dijit.MenuItem" data-dojo-props="iconClass: 'appIcon mediaPhotoFlipHorizontalIcon'">
					<?php echo $this->translator()->_('photo.edit.flipHorizontalAction'); ?>
					<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
					dojo.publish("/app/media/photo/edit/onFlip", [ "horizontal" ]);
					</script>
				</div>
				
				<div data-dojo-type="dijit.MenuItem" data-dojo-props="iconClass: 'appIcon mediaPhotoFlipVerticalIcon'">
					<?php echo $this->translator()->_('photo.edit.flipVerticalAction'); ?>
					<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
					dojo.publish("/app/media/photo/edit/onFlip", [ "vertical" ]);
					</script>
				</div>
			</div>
		</div>
		<!-- /RotateAndFlip -->
		
		<!-- Crop -->
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', showLabel: false, iconClass: 'appIcon mediaPhotoCropIcon'">
			<?php echo $this->translator()->_('photo.edit.cropAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/media/photo/edit/onCrop");
			</script>
		</button>
		<!-- /Crop -->
		
		<!-- Zoom -->
		<div data-dojo-type="dijit.form.HorizontalSlider" data-dojo-props="value: 100, minimum: 10, maximum: 200, discreteValues: 20, intermediateChanges: true, showButtons: true, style: 'width: 200px', class: 'appRight'">
			<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="value">
			dojo.publish("/app/media/photo/edit/onZoom", [ value ]);
			</script>
		</div>
		<!-- /Zoom -->
	</div>
	<!-- /Toolbar -->
	
	<!-- ImageEditor -->
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top'" class="appContentPane">
			<h2 class="appHeadline" style="margin-top: 0"><span><?php echo $this->translator()->_('photo.edit.title'); ?></span></h2>
			<div><?php echo $this->translator()->_('photo.edit.' . $this->size . 'Size'); ?></div>
		</div>
		
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center'" class="appContentPane">
			<div id="mediaPhotoEditEditorContainer" data-app-entity-props="<?php echo $this->encoder()->encode(array(
																												'photo_id' => $this->photo->photo_id,
																												'size'	   => $this->photo->size,
																												'path'	   => $this->photo->__get('image_' . $this->size),
																												'url'	   => $this->APP_ROOT_URL . $this->photo->__get('image_' . $this->size),
																											)); ?>" class="appBorderContainer" style="height: 100%; margin-top: -2px; overflow: auto; position: relative">
				<img src="<?php echo $this->APP_ROOT_URL . $this->photo->__get('image_' . $this->size); ?>" />
			</div>
		</div>
	</div>
	<!-- /ImageEditor -->
</div>

<script type="text/javascript">
dojo.require("dijit.form.Button");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.form.DropDownButton");
dojo.require("dijit.form.HorizontalSlider");
dojo.require("dijit.form.RadioButton");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.Menu");
dojo.require("dijit.MenuItem");
dojo.require("dijit.Toolbar");
dojo.require("dijit.ToolbarSeparator");
dojo.require("dijit.TooltipDialog");

dojo.registerModulePath("media", "<?php echo $this->APP_STATIC_URL; ?>/modules/media");
dojo.require("core.js.base.Encoder");
dojo.require("media.js.controllers.PhotoEditor");
dojo.require("media.js.controllers.PhotoEditorMediator");

dojo.addOnLoad(function() {
	var data = core.js.base.Encoder.decode(dojo.attr("mediaPhotoEditEditorContainer", "data-app-entity-props"));
	
	var mediaPhotoEditor = new media.js.controllers.PhotoEditor("mediaPhotoEditEditorContainer");
	mediaPhotoEditor.setOriginalImage(data.path, data.url)
					.setEditUrl("<?php echo $this->url(array(), 'media_photo_edit'); ?>" + "?photo_id=" + data.photo_id + "&size=" + data.size);
	
	var mediaPhotoEditorMediator = new media.js.controllers.PhotoEditorMediator();
	mediaPhotoEditorMediator.setUndoButton(new dijit.form.Button({
		showLabel: false,
		disabled: false,
		iconClass: "appIcon appUndoDisabledIcon",
		onClick: function() {
			mediaPhotoEditor.undo();
		}
	}, "mediaPhotoEditUndoButton"));
	mediaPhotoEditorMediator.setRedoButton(new dijit.form.Button({
		showLabel: false,
		disabled: true,
		iconClass: "appIcon appRedoDisabledIcon",
		onClick: function() {
			mediaPhotoEditor.redo();
		}
	}, "mediaPhotoEditRedoButton"));
	
	mediaPhotoEditor.setEditorMediator(mediaPhotoEditorMediator);
	
	dojo.subscribe("/app/media/photo/edit/onSave", mediaPhotoEditor, function() {
		mediaPhotoEditor.save();
	});
	dojo.subscribe("/app/media/photo/edit/onClose", mediaPhotoEditor, function() {
		mediaPhotoEditor.clean();
	});

	// Processing handler
	dojo.subscribe("/app/media/photo/edit/onRotate", mediaPhotoEditor, function(angle) {
		mediaPhotoEditor.rotate(angle);
	});
	dojo.subscribe("/app/media/photo/edit/onFlip", mediaPhotoEditor, function(direction) {
		mediaPhotoEditor.flip(direction);
	});
	dojo.subscribe("/app/media/photo/edit/onCrop", mediaPhotoEditor, function() {
		mediaPhotoEditor.toggleCropper();
	});
	dojo.subscribe("/app/media/photo/edit/onZoom", mediaPhotoEditor, function(numOfPercents) {
		mediaPhotoEditor.zoom(numOfPercents);
	});

	// Resize handler
	dojo.subscribe("/app/media/photo/edit/onSetResizeBy", mediaPhotoEditor, function(resizeBy) {
		mediaPhotoEditor.setResizeBy(resizeBy);
	});
	dojo.subscribe("/app/media/photo/edit/onSetResizeWidth", mediaPhotoEditor, function(width) {
		mediaPhotoEditor.setResizeWidth(width);
		if (mediaPhotoEditor.isMaintainRatio()) {
			dijit.byId("mediaPhotoEditResizeHeight").set("value", mediaPhotoEditor.getResizeBy() == "percentage" ? width : mediaPhotoEditor.getResizeHeight());
		}
	});
	dojo.subscribe("/app/media/photo/edit/onSetResizeHeight", mediaPhotoEditor, function(height) {
		mediaPhotoEditor.setResizeHeight(height);
		if (mediaPhotoEditor.isMaintainRatio()) {
			dijit.byId("mediaPhotoEditResizeWidth").set("value", mediaPhotoEditor.getResizeBy() == "percentage" ? height : mediaPhotoEditor.getResizeWidth());
		}
	});
	dojo.subscribe("/app/media/photo/edit/onSetMaintainRatio", mediaPhotoEditor, function(checked) {
		mediaPhotoEditor.setMaintainRatio(checked == "on");
	});
	dojo.subscribe("/app/media/photo/edit/onResize", mediaPhotoEditor, function() {
		dojo.style("mediaPhotoEditResizeDialog", "display", "none");
		mediaPhotoEditor.resize();
	});
});
</script>
