<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		message
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('message.send.title'));
?>

<form id="messageMessageSendForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', encType: 'multipart/form-data', class: 'appForm'">
<div id="messageMessageSendContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon messageSendIcon'">
			<?php echo $this->translator()->_('global._share.sendAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var _this  = this;
			var form   = dijit.byId("messageMessageSendForm");
			var params = dojo.formToObject("messageMessageSendForm");

			// I have to get the message's content manually
			params.content = tinyMCE.getInstanceById("messageMessageSendContentEditor").getContent();
			
			if (params["to_address[]"] == null || params["to_address[]"].length == 0) {
				dojo.publish("/app/global/notification", [{
					message: "<?php echo $this->translator()->_('message._share.toAddressRequired'); ?>",
					type: "error"
				}]);
				return;
			}
			if (params.content == "") {
				dojo.publish("/app/global/notification", [{
					message: "<?php echo $this->translator()->_('message._share.contentRequired'); ?>",
					type: "error"
				}]);
				return;
			}

			if (form.validate()) {
				// Disable button
				_this.set("disabled", true);
			
				dijit.byId("messageMessageSendStandby").show();
				dojo.xhrPost({
					url: "<?php echo $this->url(array(), 'message_message_send'); ?>",
					content: params,
					handleAs: "json",
					load: function(data) {
						dijit.byId("messageMessageSendStandby").hide();
						form.reset();
						_this.set("disabled", false);
						dojo.publish("/app/message/message/send/onComplete", [ data ]);
					}
				});
			}
			</script>
		</button>
	
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appCancelIcon'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/message/message/send/onCancel", [ "<?php echo $this->containerId; ?>" ]);
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', class: 'appContentPane'">
			<h2 class="appHeadline" style="margin: 0"><span><?php echo $this->translator()->_('message.send.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
			<div class="appFormRow">
				<label for="subject" class="appTopLabel"><?php echo $this->translator()->_('message._share.subject'); ?>:</label>
				<input data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="type: 'text', name: 'subject', value: '<?php if ($this->message) : ?><?php echo $this->translator()->_('message._share.replyPrefix'); ?><?php echo addslashes($this->message->subject); ?><?php endif; ?>', style: 'width: 400px', required: true, missingMessage: '<?php echo $this->translator(true)->_('message._share.subjectRequired'); ?>'" />		
			</div>
			
			<div class="appFormRow">
				<label for="subject" class="appTopLabel"><?php echo $this->translator()->_('message._share.toAddress'); ?>:</label>
				<i><?php echo $this->translator()->_('message._share.toAddressHelp'); ?></i>
			</div>
			
			<div class="appFormRow">
				<div id="messageMessageSendToAddressContainer"></div>
			</div>
			
			<div class="appFormRow">
				<label for="subject" class="appTopLabel"><?php echo $this->translator()->_('message._share.bccAddress'); ?>:</label>
			</div>
			
			<div class="appFormRow">
				<div id="messageMessageSendBccAddressContainer"></div>
			</div>

			<!-- AttachmentsUploader -->			
			<div class="appFormRow">
				<label for="subject" class="appTopLabel"><?php echo $this->translator()->_('message._share.attachments'); ?>:</label>
			</div>
			
			<div class="appFormRow">
				<div id="messageMessageSendAttachmentUploader" data-dojo-type="dojox.form.Uploader" data-dojo-props="name: 'files', multiple: true, type: 'file', uploadOnSelect: true, label: '<?php echo $this->translator(true)->_('global._share.browseFilesUploadAction'); ?>', url: '<?php echo $this->url(array(), 'message_attachment_upload'); ?>?PHPSESSID=<?php echo Zend_Session::getId(); ?>', style: 'width: 150px'">
					<script type="dojo/method" data-dojo-event="onBegin">
					this.set("disabled", true);
					dijit.byId("messageMessageSendStandby").set("imageText", "<?php echo $this->translator()->_('global._share.uploadingAction'); ?>");
					dijit.byId("messageMessageSendStandby").show();
					</script>
					<script type="dojo/method" data-dojo-event="onComplete" data-dojo-args="dataArray">
					this.set("disabled", false);
					dijit.byId("messageMessageSendStandby").hide();
					if (dataArray.length == 0) {
						dojo.publish("/app/global/notification", [{
							message: "<?php echo $this->translator()->_('message.send.cannotAttachFiles'); ?>",
							type: "error"
						}]);
						return;
					}

					dojo.style("messageMessageSendAttachmentsContainer", "display", "block");
					var sizeFormatter = file.js.views.FileFormatter.formatSize;
					var deleteFileUrl = core.js.base.controllers.ActionProvider.get("message_attachment_delete").url;

					dojo.forEach(dataArray, function(file) {
						var div = dojo.create("div", {
							style: "padding: 4px",
							className: "messageAttachment"
						}, "messageMessageSendAttachmentsContainer");
						
						// Name, extension and size of file
						dojo.create("span", {
							innerHTML: "<b>" + file.name + "</b> (." + file.extension + ", " + sizeFormatter(file.size, "0") + ")" 
						}, div);
						
						// "Delete" link to remove the attachment
						var link = dojo.create("a", {
							href: "javascript: void(0);",
							style: "padding: 0 8px",
							innerHTML: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>"
						}, div);
						dojo.connect(link, "onclick", function() {
							dojo.xhrPost({
								url: deleteFileUrl,
								content: {
									path: file.path
								},
								handleAs: "json",
								load: function(data) {
									if (data.result == "APP_RESULT_OK") {
										dojo.query(div).orphan();
										// If there is no attachments, hide the attachments container
										if (dojo.query("#messageMessageSendAttachmentsContainer .messageAttachment").length == 0) {
											dojo.style("messageMessageSendAttachmentsContainer", "display", "none");
										}
									}
								}
							});
						});
						
						// Hidden input to store the file information
						dojo.create("input", {
							type: "hidden",
							name: "attachments[]",
							value: dojo.toJson(file)
						}, div);
					});
					</script>
				</div>
			</div>
			
			<div class="appFormRow">
				<div class="appBorderContainer" id="messageMessageSendAttachmentsContainer" style="display: none"></div>
			</div>
			<!-- /AttachmentsUploader -->
			
			<div class="appFormRow">
				<label for="content" class="appTopLabel"><?php echo $this->translator()->_('message._share.content'); ?>:</label>
				<textarea id="messageMessageSendContentEditor" name="content" style="height: 300px; width: 400px"><?php if ($this->message) : ?><?php echo $this->escape('<br /><div class="messageQuote"><div class="messageQuoteSentDate">' . sprintf($this->translator()->_('message._share.sentByOnDate'), $this->user()->getById($this->message->sent_user)->user_name, $this->message->sent_date) . '</div><div class="messageQuoteContent">' . $this->message->content . '</div></div><br />'); ?><?php endif; ?></textarea>
			</div>
			
			<input type="hidden" name="format" value="json" />
			
			<?php if ($this->message) : ?>
			<input type="hidden" name="message_id" value="<?php echo $this->message->message_id; ?>" />
			<?php endif; ?>
		</div>
	</div>
</div>
</form>

<div id="messageMessageSendStandby" data-dojo-type="dojox.widget.Standby" data-dojo-props="target: 'messageMessageSendContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
dojo.registerModulePath("file", "<?php echo $this->APP_STATIC_URL; ?>/modules/file");

dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.Toolbar");
dojo.require("dojo.NodeList-traverse");
dojo.require("dojox.form.Uploader");
dojo.require("dojox.form.uploader.plugins.Flash");
dojo.require("dojox.widget.Standby");

dojo.require("core.js.base.controllers.ActionProvider");
dojo.require("core.js.views.UserCollectionView");
dojo.require("file.js.views.FileFormatter");

dojo.addOnLoad(function() {
	// Provide the actions
	<?php foreach (array(
					'message_attachment_delete',
				) as $name) : ?>
	core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
		url: "<?php echo $this->url(array(), $name); ?>",
		isAllowed: true
	});
	<?php endforeach; ?>
	
	var toUserView  = new core.js.views.UserCollectionView("messageMessageSendToAddressContainer", "to_address[]");
	var bccUserView = new core.js.views.UserCollectionView("messageMessageSendBccAddressContainer", "bcc_address[]");

	<?php if ($this->recipients && count($this->recipients) > 0) : ?>
	// Assign the from address to the "To" field
	<?php foreach ($this->recipients as $recipient) : ?>
	toUserView.addUser({
		user_id: "<?php echo $recipient->user_id; ?>",
		user_name: "<?php echo $recipient->user_name; ?>"
	});
	<?php endforeach; ?>
	<?php endif; ?>

	var handler = dojo.subscribe("/app/global/onLoadComplete/message_message_send", function() {
		// Editor to update the message's content
		tinyMCE.init({
			theme: "advanced",
			plugins: "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
			theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo",
			theme_advanced_buttons3: "link,unlink,anchor,image,cleanup,code,|,preview,|,forecolor,backcolor",
			theme_advanced_buttons4: "tablecontrols,ltr,rtl",
			theme_advanced_toolbar_location: "top",
			theme_advanced_toolbar_align: "left",
			mode: "exact",
			width: "100%",
			elements: "messageMessageSendContentEditor",
			relative_urls: false,
			content_css: "<?php echo $this->APP_STATIC_URL; ?>/modules/core/css/admin/default/styles.css",
			remove_script_host: false,
			oninit: function() {
//				dojo.publish("/app/global/onLoadComplete");
			}
		});

		dojo.unsubscribe(handler);
	});
});
</script>
