<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		message
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('message.view.title'));
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/enhanced/resources/<?php echo $this->dojoConfig()->getTheme(); ?>/EnhancedGrid.css");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/message/css/admin/default/styles.css");
</script>

<div id="messageMessageViewContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: true, style: 'padding: 0; height: 100%; width: 100%'">
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: false">
		<!-- Toolbar -->
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div id="messageMessageViewToolbar"></div>
		</div>
		<!-- /Toolbar -->
		
		<!-- Messages -->
		<div id="messageMessageViewListContainer" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
			<?php echo $this->render('message/view.ajax.phtml'); ?>
		</div>
		<!-- /Messages -->
	</div>
</div>

<script type="text/javascript">
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojox.layout.ContentPane");

dojo.require("core.js.base.controllers.ActionProvider");
dojo.require("message.js.controllers.ThreadController");
dojo.require("message.js.views.MessageContextMenu");
dojo.require("message.js.views.MessageListView");
dojo.require("message.js.views.ThreadToolbar");

dojo.addOnLoad(function() {
	var handler = dojo.subscribe("/app/global/onLoadComplete/message_message_view", function() {
		dojo.style(dojo.byId("messageMessageViewContainer").parentNode, "border", "none");
		dojo.unsubscribe(handler);
	});

	// Provide the actions
	<?php foreach (array(
					'message_message_mark', 'message_message_move', 'message_message_send', 'message_message_star',
				) as $name) : ?>
	core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
		url: "<?php echo $this->url(array(), $name); ?>",
		isAllowed: true
	});
	<?php endforeach; ?>
	
	var threadController = new message.js.controllers.ThreadController("messageMessageViewContainer");
	threadController.setMessageThreadToolbar(new message.js.views.ThreadToolbar("messageMessageViewToolbar"))
					.setMessageListView(new message.js.views.MessageListView("messageMessageViewListContainer"))
					.setMessageContextMenu(new message.js.views.MessageContextMenu())
					.initSearchCriteria(<?php echo Zend_Json::encode($this->criteria); ?>);
});
</script>
