<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		util
 * @subpackage	hooks
 * @since		1.0
 * @version		2011-12-05
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="appFormRow">
	<label for="adapter"><?php echo $this->translator()->_('config.service'); ?>:</label>
	<select data-dojo-type="dijit.form.Select" data-dojo-props="name: 'adapter'">
		<option value="TinyUrlCom">tinyurl.com</option>
		<option value="IsGd">is.gd</option>
		<option value="JdemCz">jdem.cz</option>
		<option value="MetamarkNet">metamark.net</option>
	</select>
</div>

<script type="text/javascript">
dojo.require("dijit.form.Select");
</script>
