<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('rule.role.title'));
?>

<form id="coreRuleRoleForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
<div id="coreRuleRoleContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit', iconClass: 'appIcon appSaveIcon'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var _this  = this;
			dijit.byId("coreRuleRoleStandby").show();
			dojo.publish("/app/global/notification", [{
				message: "<?php echo $this->translator()->_('global._share.savingAction'); ?>",
				type: "message"
			}]);

			_this.set("disabled", true);
			dojo.xhrPost({
				url: "<?php echo $this->url(array(), 'core_rule_role'); ?>",
				content: dojo.formToObject("coreRuleRoleForm"),
				handleAs: "json",
				load: function(data) {
					_this.set("disabled", false);
					dijit.byId("coreRuleRoleStandby").hide();
					dojo.publish("/app/core/rule/role/onComplete", [ data ]);
				}
			});
			</script>
		</button>
		
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appCancelIcon'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/core/rule/role/onCancel");
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- PermissionForm -->
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', class: 'appContentPane'">
			<h2 class="appHeadline" style="margin-top: 0">
				<span><?php echo $this->translator()->_('rule.role.title'); ?></span>
			</h2>
			
			<?php if (!$this->role) : ?>
				<?php echo $this->translator()->_('rule.role.notFound'); ?>
			<?php elseif ($this->role->isRootRole()) : ?>
				<?php echo $this->translator()->_('rule.role.cannotSetRootRole'); ?>
			<?php elseif ($this->role->locked) : ?>
				<?php echo $this->translator()->_('rule.role.cannotSetLockedRole'); ?>
			<?php else : ?>
				<?php echo sprintf($this->translator()->_('rule.role.settingHelp'), $this->role->description); ?>
			<?php endif; ?>	
		</div>

		<?php if ($this->role && !$this->role->isRootRole() && !$this->role->locked) : ?>			
		<div data-dojo-type="dijit.layout.TabContainer" data-dojo-props="region: 'center', closable: true, nested: true, class: 'appContentPane'">
			<?php foreach ($this->modules as $index => $module) : ?>
			<div data-dojo-type="dojox.layout.ContentPane" data-dojo-props="title: '<?php echo $this->extensionTranslator()->translateTitle($module); ?>', href: '<?php echo $this->url(array(), 'core_rule_role'); ?>?format=html&role_id=<?php echo $this->role->role_id; ?>&mod=<?php echo $module->name; ?>', loadingMessage: '<div class=appCenter><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>', style: 'margin-top: 8px'">
			</div>
			<?php endforeach; ?>
		</div>
		<?php endif; ?>
	</div>
	<!-- /PermissionForm -->
	
	<input type="hidden" name="format" value="json" />
	<input type="hidden" name="role_id" value="<?php echo $this->role->role_id; ?>" />
</div>
</form>

<div id="coreRuleRoleStandby" data-dojo-type="dojox.widget.Standby" data-dojo-props="target: 'coreRuleRoleContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.Toolbar");
dojo.require("dojox.layout.ContentPane");
dojo.require("dojox.widget.Standby");
</script>
