<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('accesslog.list.title'));
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/enhanced/resources/<?php echo $this->dojoConfig()->getTheme(); ?>/EnhancedGrid.css");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/core/css/admin/default/styles.css");
</script>

<div id="coreAccessLogListContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: true, style: 'padding: 0; height: 100%; width: 100%'">
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: false, class: 'appBorderContainer'">
		<!-- Toolbar -->
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div id="coreAccessLogListToolbar"></div>
		</div>
		<!-- /Toolbar -->
		
		<!-- AccessLogs -->
		<div id="coreAccessLogListGridContainer" data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
		</div>
		<!-- /AccessLogs -->
		
		<!-- Paginator -->
		<div id="coreAccessLogListPaginator" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'height: 26px; padding: -8px'">
		</div>
		<!-- /Paginator -->
	</div>
</div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('accesslog.list.title'); ?>";

dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojox.layout.ContentPane");

dojo.require("core.js.base.controllers.ActionProvider");
dojo.require("core.js.controllers.AccessLogController");
dojo.require("core.js.views.AccessLogGrid");
dojo.require("core.js.views.AccessLogToolbar");

dojo.addOnLoad(function() {
	// Provide the actions
	<?php foreach (array(
					'core_accesslog_delete', 'core_accesslog_list', 'core_accesslog_view',
				) as $name) : ?>
	core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
		url: "<?php echo $this->url(array(), $name); ?>",
		isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
	});	
	<?php endforeach; ?>

	// Create new toolbar
	var accessLogToolbar = new core.js.views.AccessLogToolbar("coreAccessLogListToolbar");
	accessLogToolbar.setModules(<?php echo $this->modules; ?>);
	accessLogToolbar.show();
	
	// Create new controller
	var accessLogController = new core.js.controllers.AccessLogController("coreAccessLogListContainer");
	accessLogController.setAccessLogToolbar(accessLogToolbar)
					   .setAccessLogGrid(new core.js.views.AccessLogGrid("coreAccessLogListGridContainer"))
					   .setAccessLogPaginator("coreAccessLogListPaginator")
					   .initSearchCriteria(<?php echo Zend_Json::encode($this->criteria); ?>)
					   .searchAccessLogs();
});
</script>
