<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-03-10
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('user.list.title'));
?>

<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false">
	<!-- Users -->
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', splitter: false, class: 'appContentPane'">
		<h2 class="appHeadline" style="margin-top: 0">
			<span><?php echo sprintf($this->translator()->_('user.list.users'), '<span class="coreUserListCounter">' . $this->total . '</span>'); ?></span>
		</h2>
		
		<?php if ($this->total == 0) : ?>
			<?php echo $this->translator()->_('user.list.notFound'); ?>
		<?php else : ?>
			<div class="coreUserItemsContainer">
			<?php foreach ($this->users as $index => $user) : ?>
				<?php echo $this->partial('user/add.ajax.phtml', array('user' => $user)); ?>
			<?php endforeach; ?>
			</div>
		<?php endif; ?>
	</div>
	<!-- /Users -->
	
	<!-- Paginator -->
	<?php if ($this->paginator->count() > 1) : ?>
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'bottom', splitter: false">
	<?php echo $this->paginator('slidingToolbar')->render($this->paginator, "javascript: dojo.publish('/app/core/user/list/onGotoPage', [__PAGE__]);"); ?>
	</div>
	<?php endif; ?>
	<!-- /Paginator -->
</div>

<script type="text/javascript">
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
</script>
