<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('openid.list.title'));
?>

<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false, class: 'appBorderContainer'">
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', class: 'appContentPane'">
		<h2 class="appHeadline" style="margin: 0"><span><?php echo $this->translator()->_('openid.list.title'); ?></span></h2>
	</div>

	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
		<?php echo $this->flashMessenger(); ?>
	
		<!-- OpenIdUrls -->
		<div style="padding-bottom: 8px" id="coreOpenIdListUrlsContainer">
		<?php if (count($this->openIdUrls) == 0) : ?>
			<?php echo $this->translator()->_('openid.list.notFound'); ?>
		<?php else : ?>
			<div style="padding-bottom: 8px"><?php echo $this->translator()->_('openid.list.help'); ?>:</div>
			
			<?php foreach ($this->openIdUrls as $url) : ?>
			<div class="coreOpenIdListUrlItem" style="padding-bottom: 4px">
				<input data-dojo-type="dijit.form.TextBox" data-dojo-props="style: 'width: 400px', disabled: true, value: '<?php echo addslashes($url); ?>'" /> 
				<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', __url: '<?php echo addslashes($url); ?>'">
					<?php echo $this->translator()->_('global._share.deleteAction'); ?>
					<script type="dojo/connect" data-dojo-event="onClick">
					var params = {
						openid_url: this.get("__url")
					};
					var button = this;
					var dialog = new dojox.widget.DialogSimple({
						title: "<?php echo $this->translator()->_('openid.delete.title'); ?>",
						loadingMessage: "<div style='text-align: center'><span class='dijitContentPaneLoading'><?php echo $this->translator()->_('global._share.loadingAction'); ?></span></div>",
						style: "width: 250px",
						refreshOnShow: true,
						onCancel: function() {
							dialog.destroyRecursive();
						}
					});
					dojo.subscribe("/app/core/openid/delete/onCancel", dialog, "onCancel");
					var handler = dojo.subscribe("/app/core/openid/delete/onComplete", dialog, function(data) {
						dialog.destroyRecursive();
						var message = (data.result == "APP_RESULT_OK")
										? "<?php echo $this->translator()->_('openid.delete.success'); ?>"
										: "<?php echo $this->translator()->_('openid.delete.error'); ?>";
						dojo.publish("/app/global/notification", [{
							message: message,
							type: (data.result == "APP_RESULT_OK") ? "message" : "error"
						}]);

						// Remove the DIV container which shows the OpenID URL and the "Delete" button
						if (data.result == "APP_RESULT_OK") {
							var container = dojo.query(button.domNode).closest(".coreOpenIdListUrlItem")[0];
							dojo.query(container).orphan();
						}

						if (dojo.query("#coreOpenIdListUrlsContainer .coreOpenIdListUrlItem").length == 0) {
							dojo.attr("coreOpenIdListUrlsContainer", {
								innerHTML: "<?php echo $this->translator()->_('openid.list.notFound'); ?>"
							});
						}

						dojo.unsubscribe(handler);
					});
					dialog.set("href", "<?php echo $this->url(array(), 'core_openid_delete'); ?>" + "?" + dojo.objectToQuery(params));
					dialog.show();
					</script>
				</button>
			</div>
			<?php endforeach; ?>
		<?php endif; ?>
		</div>
		<!-- /OpenIdUrls -->
	
		<!-- AddOpenIdUrlForm -->
		<form id="coreOpenIdListAddForm" data-dojo-type="dijit.form.Form" data-dojo-props="region: 'center', action: '<?php echo $this->url(array(), 'core_openid_add'); ?>', method: 'POST'">
			<input id="coreOpenIdListOpenIdTextBox" data-dojo-type="dijit.form.ValidationTextBox"
				data-dojo-props="type: 'text', name: 'openid_url', style: 'width: 400px', required: true, placeHolder: '<?php echo $this->translator(true)->_('user._share.openIdUrl'); ?>', promptMessage: '<?php echo $this->translator(true)->_('user._share.openIdUrlHelp'); ?>', missingMessage: '<?php echo $this->translator(true)->_('user._share.openIdUrlRequired'); ?>', invalidMessage: '<?php echo $this->translator(true)->_('user._share.openIdUrlValidator'); ?>'" />
			<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit'">
				<?php echo $this->translator()->_('global._share.addAction'); ?>
			</button>
		</form>
		<!-- /AddOpenIdUrlForm -->
	</div>
</div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('openid.list.title'); ?>";

dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojo.NodeList-traverse");
dojo.require("dojox.widget.DialogSimple");
</script>
