<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		util
 * @subpackage	plugins
 * @since		1.0
 * @version		2012-03-17
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php $this->script()->captureStart(); ?>
$(document).ready(function() {
	$("a.<?php echo $this->mailToClass; ?>").each(function() {
		var href = $(this).attr("href");
		if (href.indexOf("#MAIL:") > -1) {
			$(this).attr("href", "mailto:" + href.substring(6).split("").reverse().join(""));
		}
	});
});
<?php $this->script()->captureEnd(); ?>
