<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2011-10-31
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('task.config.title'));
?>

<div id="coreTaskConfigContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit', iconClass: 'appIcon appSaveIcon'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var _this = this;
			_this.set("disabled", true);
			dojo.publish("/app/core/task/config/onStart");
			dojo.xhrPost({
				url: "<?php echo $this->url(array(), 'core_task_config'); ?>",
				content: dojo.formToObject("coreTaskConfigForm"),
				handleAs: "json",
				load: function(data) {
					_this.set("disabled", false);
					dojo.publish("/app/core/task/config/onComplete", [ data ]);
				}
			});
			</script>
		</button>
		
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appCancelIcon'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/core/task/config/onCancel");
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- TaskConfigForm -->
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', class: 'appContentPane'">
			<h2 class="appHeadline" style="margin: 0"><span><?php echo $this->translator()->_('task.config.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
		<form id="coreTaskConfigForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
			<?php echo $this->configBody; ?>
	
			<input type="hidden" name="mod" value="<?php echo $this->module; ?>" />
			<input type="hidden" name="name" value="<?php echo $this->name; ?>" />
			<input type="hidden" name="format" value="json" />
		</form>
		</div>
	</div>
	<!-- /TaskConfigForm -->
</div>

<script type="text/javascript">
dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.Toolbar");
</script>
