<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('task.list.title'));
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/enhanced/resources/<?php echo $this->dojoConfig()->getTheme(); ?>/EnhancedGrid.css");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/core/css/admin/default/styles.css");
</script>

<div id="coreTaskListContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: true, style: 'padding: 0; height: 100%; width: 100%'">
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: false, class: 'appBorderContainer'">
		<!-- Toolbar -->
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div id="coreTaskListToolbar"></div>
		</div>
		<!-- /Toolbar -->
		
		<!-- Tasks -->
		<div id="coreTaskListGridContainer" data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
		</div>
		<!-- /Tasks -->
	</div>
</div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('task.list.title'); ?>";

dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojox.layout.ContentPane");

dojo.require("core.js.base.controllers.ActionProvider");
dojo.require("core.js.controllers.TaskController");
dojo.require("core.js.views.TaskGrid");
dojo.require("core.js.views.TaskToolbar");

dojo.addOnLoad(function() {
	// Provide the actions
	<?php foreach (array(
					'core_extension_render',
					'core_task_config', 'core_task_install', 'core_task_list', 'core_task_run', 'core_task_schedule',
					'core_task_uninstall',
				) as $name) : ?>
	core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
		url: "<?php echo $this->url(array(), $name); ?>",
		isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
	});
	<?php endforeach; ?>

	// Create new toolbar
	var taskToolbar = new core.js.views.TaskToolbar("coreTaskListToolbar");
	taskToolbar.setModules(<?php echo $this->modules; ?>);
	taskToolbar.show();
	
	// Create new controller
	var taskController = new core.js.controllers.TaskController("coreTaskListContainer");
	taskController.setTaskToolbar(taskToolbar)
				  .setTaskGrid(new core.js.views.TaskGrid("coreTaskListGridContainer"))
				  .initSearchCriteria(<?php echo Zend_Json::encode($this->criteria); ?>)
				  .searchTasks();
});
</script>
