<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-03-15
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php if ($this->playlist) : ?>

<?php $this->headTitle()->append($this->playlist->title); ?>
<div class="mediaPlaylistView">
	<h1><?php echo $this->playlist->title; ?></h1>
	
	<div class="meta">
		<?php echo date($this->translator()->_('global._share.dateFormat', 'Y-m-d'), strtotime($this->playlist->activated_date)); ?> <span>|</span> <?php echo sprintf($this->translator()->_('global._share.numViews'), $this->playlist->num_views); ?>
	</div>
	
	<div class="toolbar"></div>
	
	<?php if ($this->videos) : ?>
	<ul>
		<?php foreach ($this->videos as $video) : ?>
		<li>
			<p class="thumb">
				<a href="<?php echo $this->url(array_merge(array('playlist_id' => $this->playlist->playlist_id), $video->getProperties()), 'media_video_playlist_view'); ?>" title="<?php echo addslashes($video->title); ?>">
					<img src="<?php echo $video->getPoster('small'); ?>" title="<?php echo addslashes($video->title); ?>" />
				</a>
				<span><?php echo $video->duration; ?></span>
			</p>
			<div class="summary">
				<h2><a href="<?php echo $this->url(array_merge(array('playlist_id' => $this->playlist->playlist_id), $video->getProperties()), 'media_video_playlist_view'); ?>"><?php echo $video->title; ?></a></h2>
				<p class="meta">
					<?php echo date($this->translator()->_('global._share.dateFormat', 'Y-m-d'), strtotime($video->activated_date)); ?> <span>-</span> <?php echo sprintf($this->translator()->_('global._share.numViews'), $video->num_views); ?> <span>-</span> <?php echo sprintf($this->translator()->_('global._share.numComments'), $video->num_comments); ?> 
				</p>
				<div class="desc"><?php echo $video->description; ?></div>
			</div>
		</li>
		<?php endforeach; ?>
	</ul>
	
	<?php echo $this->paginator; ?>
	<?php endif; ?>
</div>

<?php endif; ?>
