<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		comment
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('comment.view.title'));
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/enhanced/resources/<?php echo $this->dojoConfig()->getTheme(); ?>/EnhancedGrid.css");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/comment/css/admin/default/styles.css");
</script>

<div id="commentCommentViewContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: true, style: 'padding: 0; height: 100%; width: 100%'">
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: false">
		<!-- Toolbar -->
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div id="commentCommentViewToolbar"></div>
		</div>
		<!-- /Toolbar -->
		
		<!-- Comments -->
		<div id="commentCommentViewListContainer" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
			<?php echo $this->render('comment/view.ajax.phtml'); ?>
		</div>
		<!-- /Comments -->
	</div>
</div>

<script type="text/javascript">
dojo.registerModulePath("comment", "<?php echo $this->APP_STATIC_URL; ?>/modules/comment");

dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojox.layout.ContentPane");

dojo.require("comment.js.controllers.ThreadController");
dojo.require("comment.js.views.CommentContextMenu");
dojo.require("comment.js.views.CommentListView");
dojo.require("comment.js.views.ThreadToolbar");

dojo.addOnLoad(function() {
	var handler = dojo.subscribe("/app/global/onLoadComplete/comment_comment_view", function() {
		dojo.style(dojo.byId("commentCommentViewContainer").parentNode, "border", "none");
		dojo.unsubscribe(handler);
	});
	
	var threadController = new comment.js.controllers.ThreadController("commentCommentViewContainer");
	threadController.setThreadToolbar(new comment.js.views.ThreadToolbar("commentCommentViewToolbar"))
					.setCommentListView(new comment.js.views.CommentListView("commentCommentViewListContainer"))
					.setCommentContextMenu(new comment.js.views.CommentContextMenu())
					.initSearchCriteria(<?php echo Zend_Json::encode($this->criteria); ?>);
});
</script>
