<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	plugins
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div data-dojo-type="dojox.layout.ContentPane" data-app-plugin="system" data-dojo-props="title: '<?php echo $this->translator(true)->_('debug.system.title'); ?>', selected: <?php if ($this->selected) : ?>true<?php else : ?>false<?php endif; ?>, class: 'appContentPane'">
	<?php if ($this->data) : ?>
	<div style="padding-bottom: 8px;"><?php echo $this->translator()->_('debug.system.help'); ?></div>

	<ul class="corePluginsDebugList">
		<li><?php echo sprintf($this->translator()->_('debug.system.app'), $this->data['app']); ?></li>
		<li><?php echo sprintf($this->translator()->_('debug.system.server'), $this->data['server']); ?></li>
		<li><?php echo sprintf($this->translator()->_('debug.system.php'), $this->data['php'], implode(', ', $this->data['extensions'])); ?></li>
		<li><?php echo sprintf($this->translator()->_('debug.system.zf'), $this->data['zf']); ?></li>
		<li><?php echo sprintf($this->translator()->_('debug.system.db'), $this->data['db'], $this->data['dbAdapter']); ?></li>
	</ul>
	<?php endif; ?>
</div>
