<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-05-27
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php if ($this->numPhotos == 0) : ?>
<div><?php echo $this->translator()->_('photo._share.notFound'); ?></div>
<?php else : ?>

<?php if ($this->photos) : ?>
<ul>
	<?php foreach ($this->photos as $photo) : ?>
	<li>
		<p class="thumb">
			<a href="<?php echo $this->url($photo->getProperties(), 'media_photo_view'); ?>" title="<?php echo addslashes($photo->title); ?>">
				<img src="<?php echo $photo->getThumbnail('small'); ?>" title="<?php echo addslashes($photo->title); ?>" />
			</a>
		</p>
		<?php echo Core_Base_Hook_Registry::getInstance()->executeFilter('Media_FilterPhotoTitle', '<h2><a href="' . $this->url($photo->getProperties(), 'media_photo_view') . '" title="' . addslashes($photo->title) . '">' . $photo->title . '</a></h2>'); ?>
		<p class="meta">
			<?php echo date($this->translator()->_('global._share.dateFormat', 'Y-m-d'), strtotime($photo->activated_date)); ?> <span>|</span> <?php echo sprintf($this->translator()->_('global._share.numViews'), $photo->num_views); ?> <span>|</span> <?php echo sprintf($this->translator()->_('global._share.numComments'), $photo->num_comments); ?> 
		</p>
	</li>
	<?php endforeach; ?>
</ul>

<?php echo $this->paginator; ?>
<?php endif; ?>

<?php endif; ?>
