<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		category
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('category.rename.title'));
?>

<form id="categoryCategoryRenameForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
	<script type="dojo/method" data-dojo-event="onSubmit" data-dojo-args="e">
	e.preventDefault();
	if (this.validate()) {
		var _this  = this;
		var params = dojo.formToObject("categoryCategoryRenameForm");
		dojo.xhrPost({
			url: "<?php echo $this->url(array(), 'category_category_rename'); ?>",
			content: params,
			handleAs: "json",
			load: function(data) {
				_this.reset();
				dojo.publish("/app/category/category/rename/onComplete", [ data ]);
			}
		});
	}
	</script>
	
	<div class="appFormRow">
		<label for="name" style="width: 100px"><?php echo $this->translator()->_('category._share.name'); ?>:</label>
		<div data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="type: 'text', name: 'name', value: '<?php echo addslashes($this->category->name); ?>', style: 'width: 150px', required: true, missingMessage: '<?php echo $this->translator(true)->_('category._share.nameRequired'); ?>'">
			<script type="dojo/connect" data-dojo-event="onChange" data-dojo-args="value">
			dojo.xhrPost({
				url: "<?php echo $this->url(array(), 'core_helper_slug'); ?>",
				content: {
					input: value
				},
				handleAs: "json",
				load: function(data) {
					dijit.byId("categoryCategoryRenameSlugTextBox").set("value", data.output);
				}
			});
			</script>
		</div>
	</div>
	
	<div class="appFormRow">
		<label for="slug" style="width: 100px"><?php echo $this->translator()->_('category._share.slug'); ?>:</label>
		<input id="categoryCategoryRenameSlugTextBox" data-dojo-type="dijit.form.ValidationTextBox" 
			data-dojo-props="type: 'text', name: 'slug', value: '<?php if ($this->category->slug) : ?><?php echo addslashes($this->category->slug); ?><?php endif; ?>', style: 'width: 150px', required: true, missingMessage: '<?php echo $this->translator(true)->_('category._share.slugRequired'); ?>'" />
	</div>
	
	<div class="dijitDialogPaneActionBar">
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
		</button>
		
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/category/category/rename/onCancel");
			</script>
		</button>
	</div>
	
	<input type="hidden" name="format" value="json" />
	<input type="hidden" name="category_id" value="<?php echo $this->category->category_id; ?>" />
</form>

<script type="text/javascript">
dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.ValidationTextBox");
</script>
