<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		ad
 * @subpackage	hooks
 * @since		1.0
 * @version		2012-03-22
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false">
	<!-- Banners -->
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', splitter: false, style: 'padding: 8px'">
		<div class="adHooksBannerProviderBannersContainer" data-dojo-type="dojo.dnd.AutoSource" data-dojo-props="accept: [], selfAccept: false, selfCopy: false">
			<?php if (!$this->banners || count($this->banners) == 0) : ?>
			<?php echo $this->translator()->_('show.notFound'); ?>
			<?php else : ?>
			
			<?php foreach ($this->banners as $banner) : ?>
			<div id="adHooksBannerProviderItem_<?php echo $banner->banner_id; ?>" class="adHooksBannerProviderBannerItem dojoDndItem" dndtype="adBannerItemDnd"
				data-app-entity-props="<?php echo $this->encoder()->encode($banner, array('banner_id', 'title', 'format', 'code', 'url')); ?>">
				<?php if ($banner->format == Ad_Models_Banner::FORMAT_IMAGE) : ?>
					<img src="<?php echo $this->APP_ROOT_URL . '/' . ltrim($banner->url, '/'); ?>" title="<?php echo addslashes($banner->title); ?>" />
				<?php else : ?>
					<img src="<?php echo $this->APP_ROOT_URL; ?>/modules/ad/images/defaultBanner.png" title="<?php echo addslashes($banner->title); ?>" />
				<?php endif; ?>
				<br />
				<span><?php echo $banner->title; ?></span>
			</div>
			<?php endforeach; ?>
			
			<?php endif; ?>
		</div>
	</div>
	<!-- /Banners -->
	
	<!-- Paginator -->
	<?php if ($this->paginator->count() > 1) : ?>
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'padding: -8px'">
	<?php echo $this->paginator('slidingToolbar')->render($this->paginator, "javascript: dojo.publish('/app/ad/hooks/bannerprovider/search/onGotoPage', [__PAGE__]);"); ?>
	</div>
	<?php endif; ?>
	<!-- /Paginator -->
</div>

<script type="text/javascript">
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojo.dnd.Source");
</script>
