<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	templates
 * @package		nextcms
 * @subpackage	views
 * @since		1.0
 * @version		2012-05-18
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php if ($this->numVideos > 0) : ?>
<div class="mediaWidgetsVideosList">
	<?php if ($this->title) : ?><h2><?php if ($this->link) : ?><a href="<?php echo $this->link; ?>"><?php echo $this->title; ?></a><?php else : ?><?php echo $this->title; ?><?php endif; ?></h2><?php endif; ?>
	
	<ul>
		<?php foreach ($this->videos as $video) : ?>
		<li>
			<p>
				<a href="<?php echo $this->url($video->getProperties(), 'media_video_view'); ?>" title="<?php echo addslashes($video->title); ?>"><img src="<?php echo $video->getPoster('small'); ?>" title="<?php echo addslashes($video->title); ?>" /></a>
				<span><?php echo $video->duration; ?></span>
			</p>
			<div>
				<h3><a href="<?php echo $this->url($video->getProperties(), 'media_video_view'); ?>"><?php echo $video->title; ?></a></h3>
				<span>
					<?php echo sprintf($this->translator()->_('show.by'), $video->getAuthor()); ?> <span>|</span> <?php echo sprintf($this->translator()->_('show.numViews'), $video->num_views); ?>
				</span>
			</div>
		</li>
		<?php endforeach; ?>
	</ul>
	
	<?php if ($this->link) : ?>
	<h4>
		<span><a href="<?php echo $this->link; ?>"><?php echo $this->translator()->_('show.viewAll'); ?></a></span>
	</h4>
	<?php endif; ?>
</div>
<?php endif; ?>
