<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		ad
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('zone.list.title'));
?>

<div id="adZoneListContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false, class: 'appBorderContainer'">
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', class: 'appContentPane'">
		<h2 class="appHeadline" style="margin: 0"><span><?php echo $this->translator()->_('zone.list.title'); ?></span></h2>
	</div>

	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: false, class: 'appContentPane'">
		<!-- AddNewZone -->
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', style: 'margin-bottom: 8px'">
			<div style="padding-bottom: 8px"><?php echo $this->translator()->_('zone.add.title'); ?>:</div>
		
			<form id="adZoneListAddZoneForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST'">
				<input data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="name: 'name', required: true, style: 'width: 300px', placeHolder: '<?php echo $this->translator(true)->_('zone._share.name'); ?>', missingMessage: '<?php echo $this->translator(true)->_('zone._share.nameRequired'); ?>'" />
				<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'width', style: 'width: 100px', placeHolder: '<?php echo $this->translator(true)->_('zone._share.width'); ?>'" />
				<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'height', style: 'width: 100px', placeHolder: '<?php echo $this->translator(true)->_('zone._share.height'); ?>'" />
				
				<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
					<?php echo $this->translator()->_('global._share.addAction'); ?>
					<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
					if (dijit.byId("adZoneListAddZoneForm").validate()) {
						dijit.byId("adZoneListStandby").show();
						dojo.xhrPost({
							url: "<?php echo $this->url(array(), 'ad_zone_add'); ?>",
							content: dojo.formToObject("adZoneListAddZoneForm"),
							handleAs: "json",
							load: function(data) {
								dijit.byId("adZoneListAddZoneForm").reset();
								dijit.byId("adZoneListStandby").hide();
								var message = (data.result == "APP_RESULT_OK")
												? "<?php echo $this->translator()->_('zone.add.success'); ?>"
												: "<?php echo $this->translator()->_('zone.add.error'); ?>";
								dojo.publish("/app/global/notification", [{
									message: message,
									type: (data.result == "APP_RESULT_OK") ? "message" : "error"
								}]);

								// Reload the zones
								dijit.byId("adZoneListZonesPane").set("href", "<?php echo $this->url(array(), 'ad_zone_list'); ?>?format=html");						
							}
						});
					}
					</script>
				</button>
			</form>
		</div>
		<!-- /AddNewZone -->
		
		<!-- Zones -->
		<div id="adZoneListZonesPane" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="region: 'center', href: '<?php echo $this->url(array(), 'ad_zone_list'); ?>?format=html', loadingMessage: '<div class=appCenter><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>'">
		</div>
		<!-- /Zones -->
	</div>
</div>

<div id="adZoneListStandby" data-dojo-type="dojox.widget.Standby" data-dojo-props="target: 'adZoneListContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/ad/languages')->_('zone.list.title'); ?>";

dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojox.layout.ContentPane");
dojo.require("dojox.widget.Standby");
</script>
