<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	hooks
 * @since		1.0
 * @version		2012-05-30
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div id="mediaHooksVideoProviderContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="gutters: false, title: '<?php echo $this->translator(true)->_('show.title'); ?>'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false">
		<div data-dojo-type="dijit.Toolbar">
			<input id="mediaHooksVideoProviderSearchBox" data-dojo-type="dijit.form.TextBox" data-dojo-props="type: 'text', placeHolder: '<?php echo $this->translator(true)->_('show.keywordHelp'); ?>', style: 'width: 150px'" />
			<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', showLabel: false, iconClass: 'appIcon appSearchIcon', label: '<?php echo $this->translator(true)->_('show.searchAction'); ?>'">
				<script type="dojo/connect" data-dojo-event="onClick">
				var keyword = dijit.byId("mediaHooksVideoProviderSearchBox").get("value");
				media.hooks.videoprovider.VideoController.searchVideos({
					title: keyword,
					page: 1
				});
				</script>
			</button>
		</div>
	</div>
	<!-- /Toolbar -->
	
	<!-- VideosPane -->
	<div id="mediaHooksVideoProviderVideosContainer" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="region: 'center', loadingMessage: '<div class=appCenter><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>', style: 'height: 100%; width: 100%'">
		<div class="appCenter">
			<div><?php echo $this->translator()->_('show.searchHelp'); ?></div>
		</div>
	</div>
	<!-- /VideosPane -->
</div>

<?php $this->script()->captureStart(); ?>
/* media.hooks.videoprovider */
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.Toolbar");
dojo.require("dojox.layout.ContentPane");

dojo.require("core.js.base.Encoder");
dojo.provide("media.hooks.videoprovider.VideoController");

media.hooks.videoprovider.VideoController._criteria = {
	title: null,
	page: 1,
	per_page: 20
};

media.hooks.videoprovider.VideoController.searchVideos = function(/*Object*/ criteria) {
	// summary:
	//		Searches for videos
	dojo.mixin(media.hooks.videoprovider.VideoController._criteria, criteria);
	var q = core.js.base.Encoder.encode(media.hooks.videoprovider.VideoController._criteria);

	var params = {
		_type: "hook",
		_mod: "media",
		_name: "videoprovider",
		_method: "search",
		q: q
	};
	dijit.byId("mediaHooksVideoProviderVideosContainer")
		 .set("href", "<?php echo $this->url(array(), 'core_extension_render'); ?>" + "?" + dojo.objectToQuery(params));
};

dojo.subscribe("/app/media/hooks/videoprovider/search/onGotoPage", function(/*Integer*/ page) {
	// summary:
	//		Paging handler
	media.hooks.videoprovider.VideoController.searchVideos({
		page: page
	});
});
<?php $this->script()->captureEnd(); ?>
