<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		seo
 * @subpackage	plugins
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="appFormRow">
	<label class="appTopLabel"><?php echo $this->translator()->_('config.help'); ?>:</label>
	<input data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="type: 'text', name: 'code', style: 'width: 200px', value: '<?php echo $this->code; ?>', missingMessage: '<?php echo $this->translator(true)->_('config.codeRequired'); ?>', invalidMessage: '<?php echo $this->translator(true)->_('config.codeValidator'); ?>'" />
</div>

<script type="text/javascript">
dojo.require("dijit.form.ValidationTextBox");
</script>
