<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('widget.list.title'));
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/core/css/admin/default/styles.css");
</script>

<div id="coreWidgetListContainer" class="coreExtensionItemsContainer appContentPane">
	<?php if (!$this->widgets || count($this->widgets) == 0) : ?>
		<?php echo $this->translator()->_('widget.list.notFound'); ?>
	<?php else : ?>

	<?php foreach ($this->widgets as $widget) : ?>
	<div class="coreExtensionItem">
		<div class="coreExtensionItemThumbnail">
			<img src="<?php echo $widget->thumbnail; ?>" />
		</div>
		
		<div class="coreExtensionItemDescription">
			<h3><?php echo $this->extensionTranslator()->translateTitle($widget); ?></h3>
			<div style="padding-bottom: 8px"><?php echo $this->extensionTranslator()->translateDescription($widget); ?></div>
			
			<!-- InstallButton -->
			<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', disabled: <?php if ((!$this->accessor()->route('core_widget_install') && !$widget->is_installed) || (!$this->accessor()->route('core_widget_uninstall') && $widget->is_installed)) : ?>true<?php else : ?>false<?php endif; ?>, _module: '<?php echo $widget->module; ?>', _name: '<?php echo $widget->name; ?>', _isInstalled: <?php if ($widget->is_installed) : ?>true<?php else : ?>false<?php endif; ?>">
				<?php echo $widget->is_installed ? $this->translator()->_('global._share.uninstallAction') : $this->translator()->_('global._share.installAction'); ?>
				<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
				var _this = this;
				_this.set("disabled", true);
				var isInstalled = this.get("_isInstalled");
				var module		= this.get("_module");
				var name		= this.get("_name");
				dojo.xhrPost({
					url: isInstalled ? "<?php echo $this->url(array(), 'core_widget_uninstall'); ?>" : "<?php echo $this->url(array(), 'core_widget_install'); ?>",
					content: {
						mod: module,
						name: name
					},
					handleAs: "json",
					load: function(data) {
						var message = (data.result == "APP_RESULT_OK")
									? (isInstalled ? "<?php echo $this->translator()->_('widget.uninstall.success'); ?>" : "<?php echo $this->translator()->_('widget.install.success'); ?>") 
									: (isInstalled ? "<?php echo $this->translator()->_('widget.uninstall.error'); ?>" : "<?php echo $this->translator()->_('widget.install.error'); ?>");
						dojo.publish("/app/global/notification", [{
							message: dojox.string.sprintf(message, name),
							type: (data.result == "APP_RESULT_OK") ? "message" : "error"
						}]);
						_this.set("disabled", false);

						if (data.result == "APP_RESULT_OK") {
							_this.set("_isInstalled", !isInstalled);
							_this.set("label", isInstalled ? "<?php echo $this->translator()->_('global._share.installAction'); ?>" : "<?php echo $this->translator()->_('global._share.uninstallAction'); ?>");
							dojo.publish("/app/core/widget/" + (isInstalled ? "uninstall" : "install"), [{ module: module, name: name }]);
						}
					}
				});
				</script>
			</button>
			<!-- /InstallButton -->
		</div>
		
		<div style="clear: both"></div>
	</div>
	<?php endforeach; ?>
	
	<?php endif; ?>
</div>

<script type="text/javascript">
dojo.require("dijit.form.Button");
dojo.require("dojox.string.sprintf");
</script>
