<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('language.list.title'));
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/resources/Grid.css");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/resources/<?php echo $this->dojoConfig()->getTheme(); ?>Grid.css");
</script>

<div id="coreLanguageListContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: true, style: 'height: 100%; padding: 0; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false, style: 'border-bottom: none'">
		<div id="coreLanguageListToolbar"></div>
	</div>
	<!-- /Toolbar -->
	
	<!-- LanguageGrid -->
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', style: 'height: 100%; padding: 0; width: 100%'">
		<div id="coreLanguageListGridContainer"></div>
	</div>
	<!-- /LanguageGrid -->
</div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('language.list.title'); ?>";

dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");

dojo.require("core.js.base.controllers.ActionProvider");
dojo.require("core.js.controllers.LanguageController");
dojo.require("core.js.views.LanguageGrid");
dojo.require("core.js.views.LanguageToolbar");

dojo.addOnLoad(function() {
	// Provide the actions
	<?php foreach (array(
					'core_language_add', 'core_language_delete', 'core_language_edit', 'core_language_list',
				) as $name) : ?>
	core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
		url: "<?php echo $this->url(array(), $name); ?>",
		isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
	});	
	<?php endforeach; ?>

	// Create new toolbar
	var languageToolbar = new core.js.views.LanguageToolbar("coreLanguageListToolbar");
	languageToolbar.setLanguageFiles(<?php echo Zend_Json::encode($this->languages); ?>);
	
	// Create new controller
	var languageController = new core.js.controllers.LanguageController("coreLanguageListContainer");
	languageController.setLanguageToolbar(languageToolbar)
					  .setLanguageGrid(new core.js.views.LanguageGrid("coreLanguageListGridContainer"));
});
</script>
