<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		poll
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('poll.edit.title'));
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/poll/css/admin/default/styles.css");
</script>

<div id="pollPollEditContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'headline', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
		<?php if ($this->poll) : ?>
		<button id="pollPollEditSaveButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appSaveIcon'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			if (dijit.byId("pollPollEditForm").validate()) {
				dojo.publish("/app/poll/poll/edit/onStart");
				dojo.xhrPost({
					url: "<?php echo $this->url(array(), 'poll_poll_edit'); ?>",
					content: dojo.formToObject("pollPollEditForm"),
					handleAs: "json",
					load: function(data) {
						dojo.publish("/app/poll/poll/edit/onComplete", [ data ]);
					}
				});
			}
			</script>
		</button>
		<?php endif; ?>
		
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appCancelIcon'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/poll/poll/edit/onCancel");
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="gutters: false, region: 'center'">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
			<h2 class="appHeadline" style="margin: 0"><span><?php echo $this->translator()->_('poll.edit.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
			<?php if (!$this->poll) : ?>
				<?php echo sprintf($this->translator()->_('poll.edit.notFound'), $this->pollId); ?>
			<?php else : ?>
		
			<form id="pollPollEditForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
			<div data-dojo-type="dijit.layout.TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
				<!-- Properties -->
				<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('poll._share.properties'); ?>', class: 'appContentPane'">
					<div class="appFormRow">
						<label for="language"><?php echo $this->translator()->_('poll._share.language'); ?>:</label>
						<select data-dojo-type="dijit.form.Select" data-dojo-props="name: 'language'">
						<?php foreach ($this->languages as $language => $name) : ?>
							<option value="<?php echo $language; ?>"<?php if ($language == $this->poll->language) : ?> selected="selected"<?php else : ?> disabled="disabled"<?php endif; ?>><?php echo $name; ?></option>
						<?php endforeach; ?>
						</select>
					</div>
				
					<div class="appFormRow">
						<label for="title"><?php echo $this->translator()->_('poll._share.title'); ?>:</label>
						<input data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="name: 'title', value: '<?php echo addslashes($this->poll->title); ?>', type: 'text', style: 'width: 300px', required: true, missingMessage: '<?php echo $this->translator(true)->_('poll._share.titleRequired'); ?>'" />
					</div>
					
					<div class="appFormRow">
						<label for="description"><?php echo $this->translator()->_('poll._share.description'); ?>:</label>
						<textarea data-dojo-type="dijit.form.SimpleTextarea" data-dojo-props="name: 'description', style: 'width: 300px; height: 150px'"><?php if ($this->poll->description) : ?><?php echo $this->poll->description; ?><?php endif; ?></textarea>
					</div>
					
					<div class="appFormRow">
						<label for="multiple_options">&nbsp;</label>
						<input data-dojo-type="dijit.form.CheckBox" data-dojo-props="name: 'multiple_options', value: true, checked: <?php if ($this->poll->multiple_options == "1") : ?>true<?php else : ?>false<?php endif; ?>" /> <?php echo $this->translator()->_('poll._share.multipleOptionsHelp'); ?>
					</div>
					
					<input type="hidden" name="format" value="json" />
					<input type="hidden" name="poll_id" value="<?php echo $this->poll->poll_id; ?>" />
				</div>
				<!-- /Properties -->
				
				<!-- Options -->
				<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('poll._share.options'); ?>', class: 'appContentPane'">
					<div style="padding: 8px 0">
						<?php echo $this->translator()->_('poll._share.optionHelp'); ?>
					</div>
					
					<div class="appFormRow">
						<div id="pollPollEditOptionsContainer" data-dojo-type="dojo.dnd.AutoSource" data-dojo-props="accept: ['pollOptionDnd'], selfAccept: true">
						<?php if ($this->options) : ?>
							<?php foreach ($this->options as $option) : ?>
							<div class="pollOption dojoDndItem" dndtype="pollOptionDnd">
								<input type="hidden" name="num_choices[]" value="<?php echo $option->num_choices; ?>" />
								<input data-dojo-type="dijit.form.TextBox" data-dojo-props="type: 'text', name: 'options[]', value: '<?php echo addslashes($option->title); ?>', style: 'width: 300px'" />
								<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.deleteAction'); ?>'">
									<script type="dojo/connect" data-dojo-event="onClick">
									dojo.destroy(dojo.query(this.domNode).closest(".pollOption")[0]);
									</script>
								</button>
							</div>
							<?php endforeach; ?>
						<?php endif; ?>
						</div>
					</div>
					
					<div style="padding: 8px 0">
						<input id="pollPollEditNewOption" data-dojo-type="dijit.form.TextBox" data-dojo-props="type: 'text', style: 'width: 300px', placeHolder: '<?php echo $this->translator(true)->_('poll._share.option'); ?>'" />
						<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.addAction'); ?>'">
							<script type="dojo/connect" data-dojo-event="onClick">
							// Add new option
							var div = dojo.create("div", {
								className: "pollOption dojoDndItem",
								dndtype: "pollOptionDnd"
							}, "pollPollEditOptionsContainer");
							dojo.create("input", {
								type: "hidden",
								name: "num_choices[]",
								value: 0
							}, div);
							new dijit.form.TextBox({
								name: "options[]",
								value: dijit.byId("pollPollEditNewOption").get("value"),
								style: "width: 300px"
							}).placeAt(div);
							new dijit.form.Button({
								label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
								onClick: function() {
									dojo.destroy(div);
								}
							}).placeAt(div);
							</script>
						</button>
					</div>
				</div>
				<!-- /Options -->
				
				<!-- Localization -->
				<div id="pollPollEditLocalizedContainer" data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('poll._share.localization'); ?>', class: 'appBorderContainer', style: 'margin-top: 8px'">
					<?php if ($this->translations) : ?>
					<?php foreach ($this->translations as $tranlation) : ?>
					<div class="pollPollEditLocalizedItem" style="padding: 2px 8px" data-app-translations='<?php echo $tranlation->translations; ?>'>
						<input data-dojo-type="dijit.form.TextBox" data-dojo-props="value: '<?php echo addslashes($tranlation->title); ?>', style: 'width: 300px', readOnly: true" />
						<input data-dojo-type="dijit.form.TextBox" data-dojo-props="value: '<?php echo addslashes($tranlation->language); ?>', style: 'margin: 0 8px; width: 100px', readOnly: true" />
						<input type="hidden" name="translations" value='<?php echo $tranlation->translations; ?>' />
						
						<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.deleteAction'); ?>'">
							<script type="dojo/connect" data-dojo-event="onClick">
							var localizedItem = dojo.query(this.domNode).closest(".pollPollEditLocalizedItem")[0];
							var translations  = dojo.attr(localizedItem, "data-app-translations");
							dojo.query(".pollPollEditLocalizedItem[data-app-translations='" + translations + "']", "pollPollEditLocalizedContainer").orphan();
							if (dojo.query(".pollPollEditLocalizedItem", "pollPollEditLocalizedContainer").length == 0) {
								// Show the guide
								dojo.style("pollPollEditLocalizedHelp", "display", "block");
							}
							</script>
						</button>
					</div>
					<?php endforeach; ?>
					<?php endif; ?>
					
					<div id="pollPollEditLocalizedHelp" class="appCenter" style="display: <?php if ($this->translations && count($this->translations) > 0) : ?>none<?php else : ?>block<?php endif; ?>">
						<div><?php echo $this->translator()->_('poll._share.localizationHelp'); ?></div>
					</div>
				</div>
				<!-- /Localization -->
			</div>
			</form>
			
			<?php endif; ?>
		</div>
	</div>
</div>

<script type="text/javascript">
dojo.require("dijit.Dialog");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Select");
dojo.require("dijit.form.SimpleTextarea");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.Toolbar");
dojo.require("dojo.dnd.Source");
dojo.require("dojo.NodeList-traverse");
dojo.require("dojox.grid.enhanced.plugins.GridSource");

<?php if ($this->poll) : ?>
dojo.addOnLoad(function() {
	// Allow to drag poll from the grid and drop on the localized container
	var target = new dojox.grid.enhanced.plugins.GridSource("pollPollEditLocalizedContainer", {
		isSource: false,
		insertNodesForGrid: false
	});
	dojo.connect(target, "onDropGridRows", function(grid, rowIndexes) {
		var sourceItems = [];
		dojo.forEach(rowIndexes, function(rowIndex, index) {
			var item = grid.getItem(rowIndex);
			if (item) {
				sourceItems.push(item);
			}
		});

		if (sourceItems.length > 0) {
			// Hide the guide
			dojo.style("pollPollEditLocalizedHelp", "display", "none");
		}

		dojo.forEach(sourceItems, function(item) {
			var div = dojo.create("div", {
				className: "pollPollEditLocalizedItem",
				style: "padding: 2px 8px",
				"data-app-translations": item.translations[0]
			}, "pollPollEditLocalizedContainer");

			new dijit.form.TextBox({
				value: item.title[0],
				style: "width: 300px",
				readOnly: true
			}).placeAt(div);
			
			new dijit.form.TextBox({
				value: item.language[0],
				style: "margin: 0 8px; width: 100px",
				readOnly: true
			}).placeAt(div);

			dojo.create("input", {
				name: "translations",
				type: "hidden",
				value: item.translations[0]
			}, div);

			new dijit.form.Button({
				label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
				onClick: function() {
					var localizedItem = dojo.query(this.domNode).closest(".pollPollEditLocalizedItem")[0];
					var translations  = dojo.attr(localizedItem, "data-app-translations");
					dojo.query(".pollPollEditLocalizedItem[data-app-translations='" + translations + "']", "pollPollEditLocalizedContainer").orphan();
					if (dojo.query(".pollPollEditLocalizedItem", "pollPollEditLocalizedContainer").length == 0) {
						// Show the guide
						dojo.style("pollPollEditLocalizedHelp", "display", "block");
					}
				}
			}).placeAt(div);
		});
	}); 
});
<?php endif; ?>
</script>
