<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	widgets
 * @since		1.0
 * @version		2011-11-02
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
// See http://framework.zend.com/manual/en/zend.service.flickr.html
?>
<?php if ($this->set) : ?>
<div class="mediaWidgetsFlickr">
	<ul>
		<?php foreach ($this->set as $result) : ?>
		<li>
			<a href="<?php echo $result->{$this->size}->clickUri; ?>" title="<?php echo addslashes($result->title); ?>">
				<img src="<?php echo $result->{$this->size}->uri; ?>" title="<?php echo addslashes($result->title); ?>" />
			</a>
		</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
