<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-18
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('page.edit.title'));
?>

<div id="corePageEditContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
		<?php if ($this->page) : ?>
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appSaveIcon'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			if (dijit.byId("corePageEditForm").validate()) {
				dojo.publish("/app/core/page/edit/onStart");
				dojo.xhrPost({
					url: "<?php echo $this->url(array(), 'core_page_edit'); ?>",
					content: dojo.formToObject("corePageEditForm"),
					handleAs: "json",
					load: function(data) {
						dojo.publish("/app/core/page/edit/onComplete", [ data ]);
					}
				});
			}
			</script>
		</button>
		<?php endif; ?>
		
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appCancelIcon'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/core/page/edit/onCancel");
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- AddPageForm -->
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: false">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', style: 'padding: 8px 8px 0 8px'">
			<h2 class="appHeadline" style="margin: 0"><span><?php echo $this->translator()->_('page.edit.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
			<?php if (!$this->page) : ?>
				<?php echo sprintf($this->translator()->_('page.edit.notFound'), $this->pageId); ?>
			<?php else : ?>
		
			<form id="corePageEditForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
			<div data-dojo-type="dijit.layout.TabContainer" data-dojo-props="nested: true, style: 'height: 100%'">
				<!-- Properties -->
				<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('page._share.properties'); ?>', class: 'appContentPane'">
					<div class="appFormRow">
						<label for="language"><?php echo $this->translator()->_('page._share.language'); ?>:</label>
						<select data-dojo-type="dijit.form.Select" data-dojo-props="name: 'language', value: '<?php echo $this->page->language; ?>'">
						<?php foreach ($this->languages as $language => $name) : ?>
							<option value="<?php echo $language; ?>"<?php if ($language == $this->page->language) : ?> selected="selected"<?php else : ?> disabled="disabled"<?php endif; ?>><?php echo $name; ?></option>
						<?php endforeach; ?>
						</select>
					</div>
					
					<div class="appFormRow">
						<label for="template"><?php echo $this->translator()->_('page._share.template'); ?>:</label>
						<select data-dojo-type="dijit.form.Select" data-dojo-props="name: 'template', value: '<?php echo $this->page->template; ?>'">
						<?php foreach ($this->templates as $template) : ?>
							<?php if ($template != 'admin') : ?>
							<option value="<?php echo $template; ?>"<?php if ($template == $this->page->template) : ?> selected="selected"<?php else : ?> disabled="disabled"<?php endif; ?>><?php echo $template; ?></option>
							<?php endif; ?>
						<?php endforeach; ?>
						</select>
					</div>
				
					<div class="appFormRow">
						<label for="name"><?php echo $this->translator()->_('page._share.name'); ?>:</label>
						<input id="corePageEditNameTextBox" data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="name: 'name', value: '<?php echo addslashes($this->page->name); ?>', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('page._share.nameRequired'); ?>'" />
					</div>
					
					<div class="appFormRow">
						<label for="name"><?php echo $this->translator()->_('page._share.title'); ?>:</label>
						<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'title', value: '<?php echo addslashes($this->page->title); ?>', style: 'width: 200px'" />
					</div>
					
					<div class="appFormRow">
						<label for="route"><?php echo $this->translator()->_('page._share.route'); ?>:</label>
						<select id="corePageEditRouteSelect" data-dojo-type="dijit.form.Select" data-dojo-props="name: 'route', maxHeight: 200, value: '<?php if ($this->page->route) : ?><?php echo $this->page->route; ?><?php endif; ?>'">
							<option value=""><?php echo $this->translator()->_('page._share.selectRoute'); ?></option>
							<?php if ($this->routes) : ?>
							
							<?php foreach ($this->routes as $module => $routes) : ?>
							<option type="separator"></option>
							<?php foreach ($routes as $name => $description) : ?>
							<option value="<?php echo $name; ?>"><?php echo $description; ?></option>
							<?php endforeach; ?>
							<?php endforeach; ?>
							
							<?php endif; ?>
							
							<script type="dojo/connect" data-dojo-event="onChange" data-dojo-args="value">
							if (value != "") {
								var option = dijit.byId("corePageEditRouteSelect").getOptions(value);
								dijit.byId("corePageEditNameTextBox").set("value", option.label);
							}
							</script>
						</select>
					</div>
					
					<div class="appFormRow">
						<label for="url"><?php echo $this->translator()->_('page._share.url'); ?>:</label>
						<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'url', value: '<?php if ($this->page->url) : ?><?php echo $this->page->url; ?><?php endif; ?>', style: 'width: 300px'" />
					</div>
					
					<input type="hidden" name="format" value="json" />
					<input type="hidden" name="page_id" value="<?php echo $this->page->page_id; ?>" />
				</div>
				<!-- /Properties -->
				
				<!-- Localization -->
				<div id="corePageEditLocalizedContainer" data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('page._share.localization'); ?>', class: 'appBorderContainer', style: 'margin-top: 8px'">
					<?php if ($this->translations) : ?>
					<?php foreach ($this->translations as $tranlation) : ?>
					<div class="corePageEditLocalizedItem" style="padding: 2px 8px" data-app-translations='<?php echo $tranlation->translations; ?>'>
						<input data-dojo-type="dijit.form.TextBox" data-dojo-props="value: '<?php echo addslashes($tranlation->name); ?>', style: 'width: 300px', readOnly: true" />
						<input data-dojo-type="dijit.form.TextBox" data-dojo-props="value: '<?php echo addslashes($tranlation->language); ?>', style: 'margin: 0 8px; width: 100px', readOnly: true" />
						<input type="hidden" name="translations" value='<?php echo $tranlation->translations; ?>' />
						
						<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', label: '<?php echo $this->translator(true)->_('global._share.deleteAction'); ?>'">
							<script type="dojo/connect" data-dojo-event="onClick">
							var localizedItem = dojo.query(this.domNode).closest(".corePageEditLocalizedItem")[0];
							var translations  = dojo.attr(localizedItem, "data-app-translations");
							dojo.query(".corePageEditLocalizedItem[data-app-translations='" + translations + "']", "corePageEditLocalizedContainer").orphan();
							if (dojo.query(".corePageEditLocalizedItem", "corePageEditLocalizedContainer").length == 0) {
								// Show the guide
								dojo.style("corePageEditLocalizedHelp", "display", "block");
							}
							</script>
						</button>
					</div>
					<?php endforeach; ?>
					<?php endif; ?>
					
					<div id="corePageEditLocalizedHelp" class="appCenter" style="display: <?php if ($this->translations && count($this->translations) > 0) : ?>none<?php else : ?>block<?php endif; ?>">
						<div><?php echo $this->translator()->_('page._share.localizationHelp'); ?></div>
					</div>
				</div>
				<!-- /Localization -->
			</div>
			</form>
			
			<?php endif; ?>
		</div>
	</div>
	<!-- /AddPageForm -->
</div>

<div id="corePageEditStandby" data-dojo-type="dojox.widget.Standby" data-dojo-props="target: 'corePageEditContainer', imageText: '<?php echo $this->translator(true)->_('global._share.savingAction'); ?>'"></div>

<script type="text/javascript">
dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Select");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.Toolbar");
dojo.require("dojo.NodeList-traverse");
dojo.require("dojox.grid.enhanced.plugins.GridSource");
dojo.require("dojox.widget.Standby");

dojo.addOnLoad(function() {
	var target = new dojox.grid.enhanced.plugins.GridSource("corePageEditLocalizedContainer", {
		isSource: false,
		insertNodesForGrid: false
	});
	dojo.connect(target, "onDropGridRows", function(grid, rowIndexes) {
		var sourceItems = [];
		dojo.forEach(rowIndexes, function(rowIndex, index) {
			var item = grid.getItem(rowIndex);
			if (item) {
				sourceItems.push(item);
			}
		});

		if (sourceItems.length > 0) {
			// Hide the guide
			dojo.style("corePageEditLocalizedHelp", "display", "none");
		}

		dojo.forEach(sourceItems, function(item) {
			var div = dojo.create("div", {
				className: "corePageEditLocalizedItem",
				style: "padding: 2px 8px",
				"data-app-translations": item.translations[0]
			}, "corePageEditLocalizedContainer");

			new dijit.form.TextBox({
				value: item.name[0],
				style: "width: 300px",
				readOnly: true
			}).placeAt(div);
			
			new dijit.form.TextBox({
				value: item.language[0],
				style: "margin: 0 8px; width: 100px",
				readOnly: true
			}).placeAt(div);

			dojo.create("input", {
				name: "translations",
				type: "hidden",
				value: item.translations[0]
			}, div);

			new dijit.form.Button({
				label: "<?php echo $this->translator()->_('global._share.deleteAction'); ?>",
				onClick: function() {
					var localizedItem = dojo.query(this.domNode).closest(".corePageEditLocalizedItem")[0];
					var translations  = dojo.attr(localizedItem, "data-app-translations");
					dojo.query(".corePageEditLocalizedItem[data-app-translations='" + translations + "']", "corePageEditLocalizedContainer").orphan();
					if (dojo.query(".corePageEditLocalizedItem", "corePageEditLocalizedContainer").length == 0) {
						// Show the guide
						dojo.style("corePageEditLocalizedHelp", "display", "block");
					}
				}
			}).placeAt(div);
		});
	});
});
</script>
