<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('page.import.title'));
?>

<form id="corePageImportForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '<?php echo $this->url(array(), 'core_page_import'); ?>', method: 'POST', encType: 'multipart/form-data', class: 'appForm'">
	<!-- Uploader -->
	<div class="appFormRow">
		<label for="uploader" style="width: 100px">&nbsp;</label>
		<div data-dojo-type="dojox.form.Uploader" data-dojo-props="name: 'file', multiple: true, type: 'file', uploadOnSelect: false, label: '<?php echo $this->translator(true)->_('global._share.browseFilesUploadAction'); ?>', style: 'width: 150px'">
			<script type="dojo/method" data-dojo-event="onChange" data-dojo-args="fileArray">
			dijit.byId("corePageImportSubmitButton").set("disabled", false);
			</script>
			<script type="dojo/method" data-dojo-event="onBegin" data-dojo-args="dataArray">
			this.set("disabled", true);
			</script>
			<script type="dojo/method" data-dojo-event="onComplete" data-dojo-args="dataArray">
			this.set("disabled", false);
			dojo.publish("/app/core/page/import/onSuccess", [ dataArray ]);
			</script>
		</div>
	</div>
	<!-- /Uploader -->
	
	<div class="dijitDialogPaneActionBar">
		<button id="corePageImportSubmitButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit', disabled: true">
			<?php echo $this->translator()->_('global._share.uploadAction'); ?>
		</button>
	
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/core/page/import/onCancel");
			</script>
		</button>
	</div>
	
	<input type="hidden" name="page_id" value="<?php echo $this->page_id; ?>" />
	<input type="hidden" name="format" value="json" />
</form>

<script type="text/javascript">
dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dojox.form.Uploader");
dojo.require("dojox.form.uploader.plugins.Flash");
</script>
