<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		file
 * @subpackage	views
 * @since		1.0
 * @version		2011-10-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php if ($this->bookmarks) : ?>
<?php foreach ($this->bookmarks as $bookmark) : ?>
<div id="fileBookmarkItem_<?php echo $bookmark->bookmark_id; ?>" class="fileBookmarkItem"
	data-app-entity-props="<?php echo $this->encoder()->encode($bookmark, array('connection_id', 'bookmark_id', 'name', 'path')); ?>">
	<div class="fileBookmarkUnbookmarkIcon" title="<?php echo $this->translator()->_('bookmark.list.deleteHelp'); ?>"><?php echo $this->translator()->_('bookmark.list.deleteHelp'); ?></div>
	
	<div class="fileBookmarkNameContainer">
		<a class="fileBookmarkName" title="<?php echo addslashes($bookmark->path); ?>"><?php echo $bookmark->name; ?></a>
	</div>
	
	<div class="fileBookmarkRenameIcon" title="<?php echo $this->translator()->_('bookmark.list.renameHelp'); ?>"><?php echo $this->translator()->_('bookmark.list.renameHelp'); ?></div>
</div>
<?php endforeach; ?>
<?php endif; ?>
