<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		message
 * @subpackage	views
 * @since		1.0
 * @version		2012-02-28
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('folder.delete.title'));
?>

<?php if (!$this->folder) : ?>
	<div><?php echo $this->translator()->_('folder.delete.notFound'); ?></div>
<?php else : ?>
	<div>
		<?php echo sprintf($this->translator()->_('folder.delete.confirm'), $this->folder->name); ?>
	</div>
	
	<div class="dijitDialogPaneActionBar">
		<!-- YesButton -->
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.yesMessage'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.xhrPost({
				url: "<?php echo $this->url(array(), 'message_folder_delete'); ?>",
				content: {
					folder_id: "<?php echo $this->folder->folder_id; ?>",
					format: "json"
				},
				handleAs: "json",
				load: function(data) {
					dojo.publish("/app/message/folder/delete/onComplete", [ data ]);
				}
			});
			</script>
		</button>
		<!-- /YesButton -->
		
		<!-- NoButton -->
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.noMessage'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/message/folder/delete/onCancel");
			</script>
		</button>
		<!-- /NoButton -->
	</div>
<?php endif; ?>

<script type="text/javascript">
dojo.require("dijit.form.Button");
</script>
