<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	templates
 * @package		nextcms
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-29
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="mediaWidgetsSearchbox">
	<form method="post" action="<?php echo $this->url(array(), $this->route); ?>">
		<input type="text" name="q" />
		<button type="submit"><?php echo $this->translator()->_('show.searchAction'); ?></button>
	</form>
</div>
