<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-17
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div id="appNotificationWrapper">
	<div id="appNotificationContainer">
		<?php echo $this->message; ?>
	</div>
</div>

<?php $this->script()->captureStart(); ?>
$(document).ready(function() {
	// Place the notification at the center of page
	var h = $(document).height() - $("#header").outerHeight() - $("#footer").outerHeight();
	$("#appNotificationWrapper").css("height", h + "px");
	$("#appNotificationContainer").css("padding-top", parseInt((h - $("#appNotificationContainer").outerHeight()) / 2) + "px");
});
<?php $this->script()->captureEnd(); ?>
