<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('config.config.title'));
?>

<div id="mediaConfigConfigContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%', class: 'appBorderContainer'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit', iconClass: 'appIcon appSaveIcon'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var _this = this;
			if (dijit.byId("mediaConfigConfigForm").validate()) {
				dijit.byId("mediaConfigConfigStandby").show();
				_this.set("disabled", true);

				dojo.xhrPost({
					url: "<?php echo $this->url(array(), 'media_config_config'); ?>",
					content: dojo.formToObject("mediaConfigConfigForm"),
					handleAs: "json",
					load: function(data) {
						_this.set("disabled", false);
						dijit.byId("mediaConfigConfigStandby").hide();
						dojo.publish("/app/global/notification", [{
							message: (data.result == "APP_RESULT_OK") ? "<?php echo $this->translator()->_('config.config.success'); ?>" : "<?php echo $this->translator()->_('config.config.error'); ?>",
							type: (data.result == "APP_RESULT_OK") ? "message" : "error"
						}]);
					}
				});
			}
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- ConfigForm -->
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center'" class="appContentPane">
		<form id="mediaConfigConfigForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
			<h2 class="appHeadline" style="margin-top: 0"><span><?php echo $this->translator()->_('config.config.title'); ?></span></h2>
			
			<div data-dojo-type="dijit.layout.TabContainer" data-dojo-props="closable: true, nested: true, style: 'height: 100%'">
				<!-- FlickrImporter -->
				<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config.config.flickr'); ?>', class: 'appContentPane'">
					<div class="appFormRow">
						<label for="flickr_api_key"><?php echo $this->translator()->_('config.config.apiKey'); ?>:</label>
						<input data-dojo-type="dijit.form.TextBox" data-dojo-props="type: 'text', name: 'flickr_api_key', value: '<?php echo $this->config('media', 'flickr_api_key'); ?>', style: 'width: 300px'" />
					</div>
					
					<div class="appFormRow">
						<label for="flickr_secret_key"><?php echo $this->translator()->_('config.config.secretKey'); ?>:</label>
						<input data-dojo-type="dijit.form.TextBox" data-dojo-props="type: 'text', name: 'flickr_secret_key', value: '<?php echo $this->config('media', 'flickr_secret_key'); ?>', style: 'width: 300px'" />
					</div>
				</div>
				<!-- /FlickrImporter -->
			</div>
			
			<input type="hidden" name="format" value="json" />
		</form>
	</div>
	<!-- /ConfigForm -->
</div>

<div id="mediaConfigConfigStandby" data-dojo-type="dojox.widget.Standby" data-dojo-props="target: 'mediaConfigConfigContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/media/languages')->_('config.config.title'); ?>";

dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.Toolbar");
dojo.require("dojox.widget.Standby");
</script>
