<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-05-30
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->style()->appendStylesheet($this->APP_STATIC_URL . '/modules/core/css/admin/default/styles.css')
			  ->appendStylesheet($this->APP_STATIC_URL . '/static/js/dojo/' . APP_DOJO_VER . '/dojox/layout/resources/GridContainer.css')
			  ->appendStylesheet($this->APP_STATIC_URL . '/static/js/dojo/' . APP_DOJO_VER . '/dojox/widget/Portlet/Portlet.css');
$this->headTitle()->set($this->translator()->_('dashboard.index.title'));
?>

<div id="coreDashboardIndexContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'headline', gutters: true, region: 'center', style: 'height: 100%; padding: 0; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false, style: 'height: 26px'">
		<div id="coreDashboardIndexToolbar"></div>
	</div>
	<!-- /Toolbar -->
	
	<!-- Layout -->
	<div id="coreDashboardIndexLayout" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', style: 'height: 100%; width: 100%', class: 'appLayoutBorderContainer'">
	</div>
	<!-- /Layout -->
</div>

<?php $this->script()->captureStart(); ?>
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");

dojo.registerModulePath("core", "<?php echo $this->APP_STATIC_URL; ?>/modules/core");
dojo.require("core.js.base.controllers.ActionProvider");
dojo.require("core.js.controllers.LayoutController");
dojo.require("core.js.base.views.Helper");
dojo.require("core.js.views.LayoutToolbar");

dojo.addOnLoad(function() {
	// Don't load the widgets on user's dashboard if user is viewing other page
	if (dojo.hash() == "") {
		// Provide the actions
		<?php foreach (array(
						'core_extension_render',
					) as $name) : ?>
		core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
			url: "<?php echo $this->url(array(), $name); ?>",
			isAllowed: true
		});
		<?php endforeach; ?>
	
		var layoutData = <?php if ($this->layout) : ?><?php echo $this->layout; ?><?php else : ?>{"containers":[{"containers":[],"cls":"dojox.layout.GridContainer","numZones":3}],"cls":"dijit.layout.BorderContainer","region":"center","style":"height: 100%; width: 100%"}<?php endif; ?>;
		
		var layoutController = new core.js.controllers.LayoutController("coreDashboardIndexLayout");
		layoutController.setLayoutToolbar(new core.js.views.LayoutToolbar("coreDashboardIndexToolbar"))
						.setLayoutData(layoutData);
		layoutController.switchToMode("preview");
		
		// Save layout handler
		var helper = new core.js.base.views.Helper("coreDashboardIndexContainer");
		dojo.connect(layoutController, "onSaveLayout", function(layoutData) {
			helper.setModule("core").showStandby();
			dojo.xhrPost({
				url: "<?php echo $this->url(array(), 'core_dashboard_index'); ?>",
				content: {
					format: "json",
					layout: dojo.toJson(layoutData)
				},
				handleAs: "json",
				load: function(data) {
					helper.hideStandby();
					var message = (data.result == "APP_RESULT_OK")
									? "<?php echo $this->translator()->_('dashboard.index.success'); ?>" 
									: "<?php echo $this->translator()->_('dashboard.index.error'); ?>";
					dojo.publish("/app/global/notification", [{
						message: message,
						type: (data.result == "APP_RESULT_OK") ? "message" : "error"
					}]);
					
					if (data.result == "APP_RESULT_OK") {
						layoutController.setLayoutData(layoutData);
					}
				}
			});
		});
	}
});
<?php $this->script()->captureEnd(); ?>
