<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		tag
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-01
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('tag.list.title'));
?>

<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false">
	<!-- Tags -->
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', splitter: false, style: 'padding: 8px'">
		<h2 class="appHeadline" style="margin-top: 0">
			<span><?php echo sprintf($this->translator()->_('tag.list.tags'), '<span class="tagTagListCounter">' . $this->total . '</span>'); ?></span>
		</h2>
		
		<?php if ($this->total == 0) : ?>
			<?php echo $this->translator()->_('tag.list.notFound'); ?>
		<?php else : ?>
			<?php foreach ($this->tags as $tag) : ?>
			<div id="tagTagListItem_<?php echo $tag->tag_id; ?>" class="tagTagItem" data-app-entity-props="<?php echo $this->encoder()->encode($tag); ?>">
				<?php echo $tag->title; ?>
			</div>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
	<!-- /Tags -->
	
	<!-- Paginator -->
	<?php if ($this->paginator->count() > 1) : ?>
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'padding: -8px'">
	<?php echo $this->paginator('slidingToolbar')->render($this->paginator, "javascript: dojo.publish('/app/tag/tag/list/onGotoPage', [__PAGE__]);"); ?>
	</div>
	<?php endif; ?>
	<!-- /Paginator -->
</div>

<script type="text/javascript">
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
</script>
