<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/media/widgets/videos/admin.css");
</script>

<div class="appForm">
	<div class="appFormRow" style="width: 100%">
		<div data-dojo-type="dijit.layout.TabContainer" data-dojo-props="nested: true, style: 'height: 100%; width: 100%', closable: true, doLayout: false">
			<!-- Basic -->
			<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="selected: true, title: '<?php echo $this->translator(true)->_('config.basic'); ?>', style: 'padding-top: 8px'">
				<div class="appFormRow">
					<label class="appTopLabel" for="lang"><?php echo $this->translator()->_('config.language'); ?>:</label>
					<select data-dojo-type="dijit.form.Select" data-dojo-props="name: 'language', value: '<?php echo $this->language; ?>', class: 'appWidgetInput'">
						<?php if ($this->languages) : ?>
						<?php foreach ($this->languages as $language => $name) : ?>
						<option value="<?php echo $language; ?>"><?php echo $name; ?></option>
						<?php endforeach; ?>
						<?php endif; ?>
						
						<script type="dojo/connect" data-dojo-event="onChange" data-dojo-args="value">
						// Update the category select box
						dojo.xhrPost({
							url: "<?php echo $this->url(array(), 'core_extension_render'); ?>",
							content: {
								_type: "widget",
								_mod: "media",
								_name: "videos",
								_method: "playlist",
								noRenderScript: true,
								language: value
							},
							handleAs: "json",
							load: function(data) {
								var playlistSelect = dijit.byId("mediaWidgetsVideosConfigPlaylistSelect_<?php echo $this->uid; ?>");
								playlistSelect.store = new dojo.data.ItemFileReadStore({
									data: data
								});
							}
						});
						</script>
					</select>
				</div>
			
				<div class="appFormRow">
					<label class="appTopLabel" for="limit"><?php echo $this->translator()->_('config.numberOfVideos'); ?>:</label>
					<input data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="name: 'limit', class: 'appWidgetInput', style: 'width: 100px'" />
				</div>
				
				<div class="appFormRow">
					<label class="appTopLabel" for="playlist_id"><?php echo $this->translator()->_('config.playlist'); ?>:</label>
					<select id="mediaWidgetsVideosConfigPlaylistSelect_<?php echo $this->uid; ?>" data-dojo-type="dijit.form.FilteringSelect" data-dojo-props="name: 'playlist_id', value: '<?php echo $this->playlist_id; ?>', searchAttr: 'title', class: 'appWidgetInput'">
						<script type="dojo/connect">
						this.store = new dojo.data.ItemFileReadStore({
							data: <?php echo $this->playlists; ?>
						});
						</script>
					</select>
				</div>
				
				<div class="appFormRow">
					<label class="appTopLabel" for="keyword"><?php echo $this->translator()->_('config.keyword'); ?>:</label>
					<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'keyword', class: 'appWidgetInput'" />
				</div>
			</div>
			<!-- /Basic -->
			
			<!-- DataSource -->
			<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config.dataSource'); ?>', style: 'padding-top: 8px'">
				<div class="appFormRow">
					<div data-dojo-type="dijit.form.RadioButton" data-dojo-props="type: 'radio', name: 'data_source', value: 'latest', class: 'appWidgetInput'">
						<script type="dojo/connect" data-dojo-event="onChange" data-dojo-args="value">
						if (value) {
							dojo.style("mediaWidgetsVideosConfigSetContainer_<?php echo $this->uid; ?>", "display", "none");
						}
						</script>
					</div>
					<?php echo $this->translator()->_('config.latestVideos'); ?>
				</div>
				
				<div class="appFormRow">
					<div data-dojo-type="dijit.form.RadioButton" data-dojo-props="type: 'radio', name: 'data_source', value: 'most_commented', class: 'appWidgetInput'">
						<script type="dojo/connect" data-dojo-event="onChange" data-dojo-args="value">
						if (value) {
							dojo.style("mediaWidgetsVideosConfigSetContainer_<?php echo $this->uid; ?>", "display", "none");
						}
						</script>
					</div>
					<?php echo $this->translator()->_('config.mostCommentedVideos'); ?>
				</div>
				
				<div class="appFormRow">
					<div data-dojo-type="dijit.form.RadioButton" data-dojo-props="type: 'radio', name: 'data_source', value: 'most_viewed', class: 'appWidgetInput'">
						<script type="dojo/connect" data-dojo-event="onChange" data-dojo-args="value">
						if (value) {
							dojo.style("mediaWidgetsVideosConfigSetContainer_<?php echo $this->uid; ?>", "display", "none");
						}
						</script>
					</div>
					<?php echo $this->translator()->_('config.mostViewedVideos'); ?>
				</div>
				
				<div class="appFormRow">
					<div data-dojo-type="dijit.form.RadioButton" data-dojo-props="type: 'radio', name: 'data_source', value: 'set', class: 'appWidgetInput'">
						<script type="dojo/connect" data-dojo-event="onChange" data-dojo-args="value">
						if (value) {
							dojo.style("mediaWidgetsVideosConfigSetContainer_<?php echo $this->uid; ?>", "display", "block");
						}
						</script>
					</div>
					<?php echo $this->translator()->_('config.setOfVideos'); ?>
				</div>
				
				<div class="appFormRow" id="mediaWidgetsVideosConfigSetContainer_<?php echo $this->uid; ?>" style="display: none; margin: 0 5px">
					<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="style: 'height: 200px; padding: 0; width: 100%', class: 'appBorderContainer'">
						<div id="mediaWidgetsVideosConfigVideosContainer_<?php echo $this->uid; ?>" class="mediaWidgetsVideosConfigVideoItemsContainer" style="height: 100%">
							<div id="mediaWidgetsVideosConfigSetHelp_<?php echo $this->uid; ?>" style="display: <?php if (count($this->videos) == 0) : ?>block<?php else : ?>none<?php endif; ?>; padding-top: 100px; text-align: center">
								<?php echo $this->translator()->_('config.dragDropHelp'); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /DataSource -->
			
			<!-- Theme -->
			<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config.theme'); ?>', style: 'padding-top: 8px'">
				<div class="appFormRow">
					<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'theme', class: 'appWidgetInput'" />
				</div>
			</div>
			<!-- /Theme -->
		</div>
	</div>
</div>

<script type="text/javascript">
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.Select");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.layout.TabContainer");
dojo.require("dojo.data.ItemFileReadStore");
dojo.require("dojo.dnd.Source");
dojo.require("dojo.window");
dojo.require("dojox.fx");

dojo.require("core.js.base.Encoder");
dojo.require("core.js.Constant");

dojo.provide("media.widgets.videos.ConfigController");

// Array of video's Ids in the set
media.widgets.videos.ConfigController._videoIds = [];

media.widgets.videos.ConfigController.addVideo = function(/*Object*/ video, /*String*/ uid) {
	// summary:
	//		Adds a video to the set
	// video:
	//		The video data, contains the following properties:
	//		- title
	//		- video_id
	//		- image_square
	// uid:
	//		The unique Id which can be used to define the set container
	if (dojo.indexOf(media.widgets.videos.ConfigController._videoIds, video.video_id) != -1) {
		return;
	}
	media.widgets.videos.ConfigController._videoIds.push(video.video_id);
	
	var div = dojo.create("div", {
		className: "dojoDndItem mediaWidgetsVideosConfigVideoItem",
		dndtype: "mediaWidgetsVideosConfigVideoItemDnd"
	}, "mediaWidgetsVideosConfigVideosContainer_" + uid);

	// Video poster
	dojo.create("img", {
		src: core.js.Constant.normalizeUrl(video.image_square),
		title: video.title,
		className: "appLeft"
	}, div);

	dojo.create("br", {}, div);
	
	// Removing action
	var removingLink = dojo.create("a", {
		href: "javascript: void(0);",
		innerHTML: "<?php echo $this->translator()->_('config.removeAction'); ?>"
	}, div);
	dojo.connect(removingLink, "onclick", function() {
		dojo.destroy(div);
		var index = dojo.indexOf(media.widgets.videos.ConfigController._videoIds, video.video_id);
		media.widgets.videos.ConfigController._videoIds.splice(index, 1);
		
		// Show the guide if there is no videos
		if (dojo.query(".mediaWidgetsVideosConfigVideoItem", "mediaWidgetsVideosConfigVideosContainer_" + uid).length == 0) {
			dojo.style("mediaWidgetsVideosConfigSetHelp_" + uid, "display", "block");
		}
	});

	// Hidden input
	dojo.create("input", {
		type: "hidden",
		appWidgetInputName: "video_ids[]",
		name: "video_ids[]",
		value: video.video_id,
		className: "appWidgetInput"
	}, div);
	
	dojo.create("div", {
		className: "appClear"
	}, div);	
};

dojo.addOnLoad(function() {
	// Load the videos in set
	<?php foreach ($this->videos as $video) : ?>
	media.widgets.videos.ConfigController.addVideo(<?php echo Zend_Json::encode($video); ?>, "<?php echo $this->uid; ?>");
	<?php endforeach; ?>
	
	new dojo.dnd.AutoSource("mediaWidgetsVideosConfigVideosContainer_<?php echo $this->uid; ?>", {
		accept: ["mediaVideoDndItem"],
		onDropExternal: function(source, nodes, copy) {
			var node = nodes[0];
			if (dojo.attr(node, "data-app-entity-class") != "Media_Models_Video") {
				return;
			}

			// Hide the guides
			dojo.style("mediaWidgetsVideosConfigSetHelp_<?php echo $this->uid; ?>", "display", "none");
			
			var video = core.js.base.Encoder.decode(dojo.attr(node, "data-app-entity-props"));
			media.widgets.videos.ConfigController.addVideo(video, "<?php echo $this->uid; ?>");
		}
	});
});
</script>
