<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		file
 * @subpackage	views
 * @since		1.0
 * @version		2011-10-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('connection.list.title'));
?>

<?php if ($this->connections) : ?>
<ul class="fileConnectionItemsContainer">
	<?php foreach ($this->connections as $connection) : ?>
	<li id="fileConnectionItem_<?php echo $connection->connection_id; ?>" class="fileConnectionItem"
		data-app-entity-props="<?php echo $this->encoder()->encode(array(
																	'connection_id' => $connection->connection_id,
																	'name'			=> $connection->name,
																	'is_connected'  => false,
																)); ?>">
		<span class="fileConnectionName"><?php echo $connection->name; ?></span>
	</li>
	<?php endforeach; ?>
</ul>
<?php endif; ?>
