<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		menu
 * @subpackage	views
 * @since		1.0
 * @version		2012-06-12
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('menu.list.title'));
?>

<script type="text/javascript">
dojo.require("core.js.base.Resource");
core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/static/js/dojo/<?php echo APP_DOJO_VER; ?>/dojox/grid/enhanced/resources/<?php echo $this->dojoConfig()->getTheme(); ?>/EnhancedGrid.css");
</script>

<div id="menuMenuListContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: true, style: 'padding: 0; height: 100%; width: 100%'">
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: false, class: 'appBorderContainer'">
		<!-- Toolbar -->
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div id="menuMenuListToolbar"></div>
		</div>
		<!-- /Toolbar -->
		
		<!-- Menus -->
		<div id="menuMenuListGridContainer" data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
		</div>
		<!-- /Menus -->
		
		<!-- Paginator -->
		<div id="menuMenuListPaginator" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'height: 26px; padding: -8px'">
		</div>
		<!-- /Paginator -->
	</div>
</div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/menu/languages')->_('menu.list.title'); ?>";
dojo.registerModulePath("menu", "<?php echo $this->APP_STATIC_URL; ?>/modules/menu");

dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojox.layout.ContentPane");

dojo.require("core.js.base.Config");
dojo.require("core.js.base.controllers.ActionProvider");
dojo.require("menu.js.controllers.MenuController");
dojo.require("menu.js.views.MenuGrid");
dojo.require("menu.js.views.MenuToolbar");

dojo.addOnLoad(function() {
	// Provide the actions
	<?php foreach (array(
					'menu_menu_add', 'menu_menu_delete', 'menu_menu_edit', 'menu_menu_list',
				) as $name) : ?>
	core.js.base.controllers.ActionProvider.set("<?php echo $name; ?>", {
		url: "<?php echo $this->url(array(), $name); ?>",
		isAllowed: <?php if ($this->accessor()->route($name)) : ?>true<?php else : ?>false<?php endif; ?>
	});	
	<?php endforeach; ?>

	// Localization
	core.js.base.Config.set("core", "localization_languages", <?php echo $this->config("core", "localization_languages", '{"en_US":"English"}'); ?>);

	var menuController = new menu.js.controllers.MenuController("menuMenuListContainer");
	menuController.setMenuToolbar(new menu.js.views.MenuToolbar("menuMenuListToolbar"))
				  .setMenuGrid(new menu.js.views.MenuGrid("menuMenuListGridContainer"))
				  .setMenuPaginator("menuMenuListPaginator")
				  .initSearchCriteria(<?php echo Zend_Json::encode($this->criteria); ?>)
				  .searchMenus();
});
</script>
