<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	templates
 * @package		nextcms
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-27
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php if ($this->article) : ?>

<?php $this->headTitle()->append($this->article->title); ?>
<div class="contentArticleView">
	<div class="content">
		<?php echo $this->article->content; ?>
	</div>
</div>

<?php endif; ?>
