<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-05-17
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php $this->headTitle()->append($this->translator()->_('video.index.title')); ?>

<div class="mediaVideosList">
	<h1><?php echo $this->translator()->_('video.index.title'); ?></h1>
	<?php echo $this->render('_partial/_videos.phtml'); ?>
</div>
