<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-03-16
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('video.list.title'));
?>

<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false">
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', splitter: false, style: 'padding: 8px'">
		<h2 class="appHeadline" style="margin-top: 0">
			<span><?php echo sprintf($this->translator()->_('video.list.total'), '<span class="mediaVideoListCounter">' . $this->total . '</span>'); ?></span>
		</h2>

		<?php if ($this->total == 0) : ?>
		<?php echo $this->translator()->_('video._share.notFound'); ?>
		<?php else : ?>

		<div class="mediaVideoItemsContainer">
			<?php foreach ($this->videos as $index => $video) : ?>
			<div class="mediaVideoItem dojoDndItem" id="mediaVideoItem_<?php echo $video->video_id; ?>" 
				<?php if ($this->accessor()->route('media_video_copy')) : ?>dndtype="mediaVideoItemDnd" <?php endif; ?>
				data-app-entity-props="<?php echo $this->encoder()->encode(array(
																			'view_size' => $this->criteria['view_size'],
																			'video_id'	=> $video->video_id,
																			'status'	=> $video->status,
																			'title'		=> $video->title,
																			'url'		=> $video->url ? $video->url : '',
																			'square'	=> $video->getPoster('square'),
																			'thumbnail' => $video->getPoster('thumbnail'),
																			'small'		=> $video->getPoster('small'),
																			'crop'		=> $video->getPoster('crop'),
																			'medium'	=> $video->getPoster('medium'),
																			'large'		=> $video->getPoster('large'),
																		)); ?>">
				<div class="mediaVideoItemPoster">
					<div class="mediaVideoItemPlayIcon"></div>
					<img class="mediaVideoImage"
						src="<?php echo $video->getPoster($this->criteria['view_size']); ?>"
						title="<?php echo addslashes($video->title); ?>" />
				</div>
				
				<div class="mediaVideoItemTitle"><?php echo $video->title; ?></div>
			</div>
			<?php endforeach; ?>
		</div>
		
		<?php endif; ?>
	</div>

	<!-- Paginator -->
	<?php if ($this->paginator->count() > 1) : ?>
	<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'bottom', splitter: false, style: 'padding: -8px'">
		<?php echo $this->paginator('slidingToolbar')->render($this->paginator, "javascript: dojo.publish('/app/media/video/list/onGotoPage', [__PAGE__]);"); ?>
	</div>
	<?php endif; ?>
	<!-- /Paginator -->
</div>

<script type="text/javascript">
dojo.require("dijit.layout.BorderContainer");
dojo.require("dijit.layout.ContentPane");
</script>
