<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		media
 * @subpackage	views
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('video.rename.title'));
?>

<form id="mediaVideoRenameForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
	<script type="dojo/method" data-dojo-event="onSubmit" data-dojo-args="e">
	e.preventDefault();
	var _this = this;
	if (_this.validate()) {
		dojo.xhrPost({
			url: "<?php echo $this->url(array(), 'media_video_rename'); ?>",
			content: dojo.formToObject("mediaVideoRenameForm"),
			handleAs: "json",
			load: function(data) {
				dojo.publish("/app/media/video/rename/onComplete", [ data ]);
			}
		});
	}
	</script>

	<?php if (!$this->video) : ?>
		<?php echo sprintf($this->translator()->_('video.rename.notFound'), $this->videoId); ?>
	<?php else : ?>

	<div class="appFormRow">
		<label for="title"><?php echo $this->translator()->_('video._share.title'); ?>:</label>
		<div data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="type: 'text', name: 'title', value: '<?php echo addslashes($this->video->title); ?>', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('video._share.titleRequired'); ?>'">
			<script type="dojo/connect" data-dojo-event="onChange" data-dojo-args="value">
			dojo.xhrPost({
				url: "<?php echo $this->url(array(), 'core_helper_slug'); ?>",
				content: {
					input: value
				},
				handleAs: "json",
				load: function(data) {
					dijit.byId("mediaVideoRenameSlugTextBox").set("value", data.output);
				}
			});
			</script>
		</div>
	</div>
	
	<div class="appFormRow">
		<label for="slug"><?php echo $this->translator()->_('video._share.slug'); ?>:</label>
		<input id="mediaVideoRenameSlugTextBox" data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="type: 'text', name: 'slug', value: '<?php echo addslashes($this->video->slug); ?>', style: 'width: 200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('video._share.slugRequired'); ?>'" />
	</div>
	
	<?php endif; ?>

	<div class="dijitDialogPaneActionBar">
		<?php if ($this->video) : ?>
		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
		</button>
		<?php endif; ?>

		<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			dojo.publish("/app/media/video/rename/onCancel");
			</script>
		</button>
	</div>

	<input type="hidden" name="format" value="json" />
	<input type="hidden" name="video_id" value="<?php echo $this->videoId; ?>" />
</form>

<script type="text/javascript">
dojo.require("dijit.form.Button");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.ValidationTextBox");
</script>
