<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		util
 * @subpackage	hooks
 * @since		1.0
 * @version		2012-04-29
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php $this->script()->captureStartOnce('utilHooksNavigatorShow'); ?>
$(document).ready(function() {
	// Toggle the table of contents
	$(".utilHooksNavigatorToggle").click(function() {
		$(this).parents(".utilHooksNavigator").find(".utilHooksNavigatorToc").toggle();
		$(this).html("[-]" == $(this).html() ? "[+]" : "[-]");
	});
	$(window).scroll(function() {
		var targetTop = $(".utilHooksNavigatorTarget").eq(0).offset().top;
		if ($(window).scrollTop() > targetTop) {
			$(".utilHooksNavigator").css("top", "10px");
		} else {
			$(".utilHooksNavigator").css("top", targetTop + "px");
		}
	});
});
<?php $this->script()->captureEndOnce('utilHooksNavigatorShow'); ?>
