<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		content
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-03-29
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php if ($this->numArticles > 0) : ?>
<div class="contentWidgetsArticlesPhoto">
	<?php if ($this->title) : ?><h2><?php echo $this->title; ?></h2><?php endif; ?>
	
	<div class="main">
		<a href="<?php echo $this->articles[0]->getViewUrl(); ?>" title="<?php echo addslashes($this->articles[0]->title); ?>">
			<img src="<?php echo $this->articles[0]->getCover('crop'); ?>" title="<?php echo addslashes($this->articles[0]->getCoverTitle()); ?>" height="225" width="300" />
		</a>
		<div>
			<h3><a href="<?php echo $this->articles[0]->getViewUrl(); ?>"><?php echo $this->articles[0]->title; ?></a></h3>
			<span>
				<?php echo sprintf($this->translator()->_('show.by'), $this->articles[0]->getAuthor()); ?> <span>|</span> <?php echo $this->dateFormatter()->diff(strtotime($this->articles[0]->activated_date), $this->timeDiffFormats); ?> 
			</span>
		</div>
	</div>
	
	<ul>
		<?php for ($i = 1; $i < $this->numArticles; $i++) : ?>
		<li>
			<h3><a href="<?php echo $this->articles[$i]->getViewUrl(); ?>"><?php echo $this->articles[$i]->title; ?></a></h3>
			<span>
				<?php echo sprintf($this->translator()->_('show.by'), $this->articles[$i]->getAuthor()); ?> <span>|</span> <?php echo $this->dateFormatter()->diff(strtotime($this->articles[$i]->activated_date), $this->timeDiffFormats); ?> 
			</span>
		</li>
		<?php endfor; ?>
	</ul>
</div>
<?php endif; ?>
