<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		content
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-03-29
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php if ($this->numArticles > 0) : ?>
<div class="contentWidgetsArticlesMostViewed">
	<h2><?php if ($this->title) : ?><?php echo $this->title; ?><?php else : ?><?php echo $this->translator()->_('show.mostViewed'); ?><?php endif; ?></h2>
	
	<ul>
		<?php foreach ($this->articles as $article) : ?>
		<li>
			<p>
				<a href="<?php echo $article->getViewUrl(); ?>" title="<?php echo addslashes($article->title); ?>"><img src="<?php echo $article->getCover('square'); ?>" title="<?php echo addslashes($article->getCoverTitle()); ?>" height="75" width="75" /></a>
				<span><?php echo $article->num_views; ?></span>
			</p>
			<div>
				<h3><a href="<?php echo $article->getViewUrl(); ?>"><?php echo $article->title; ?></a></h3>
				<span>
					<?php echo sprintf($this->translator()->_('show.by'), $article->getAuthor()); ?> <span>|</span> <?php echo sprintf($this->translator()->_('show.numComments'), $article->num_comments); ?> <span>|</span> <?php echo $this->dateFormatter()->diff(strtotime($article->activated_date), $this->timeDiffFormats); ?>
				</span>
			</div>
		</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
