<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	templates
 * @package		nextcms
 * @subpackage	layouts
 * @since		1.0
 * @version		2012-05-21
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<p>
	&copy; <?php echo date('Y'); ?> Nguyen Huu Phuoc. All rights reserved.
	<br />
	This website is powered by NextCMS
	<br />
	<a href="mailto:thenextcms@gmail.com">thenextcms@gmail.com</a> | <a href="http://twitter.com/thenextcms" title="Follow NextCMS on Twitter">@thenextcms</a> | <a href="http://gplus.to/thenextcms" title="Follow NextCMS on Google+">+thenextcms</a>
</p>
