<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		util
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-04-06
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<div class="appForm">
	<div class="appFormRow" style="width: 100%">
		<div data-dojo-type="dijit.layout.TabContainer" data-dojo-props="nested: true, style: 'height: 100%; width: 100%', closable: true, doLayout: false">
			<!-- Basic -->
			<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="selected: true, title: '<?php echo $this->translator(true)->_('config.basic'); ?>', style: 'padding-top: 8px'">
				<div class="appFormRow">
					<label class="appTopLabel" for="limit"><?php echo $this->translator()->_('config.numberOfMessages'); ?>:</label>
					<input data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="name: 'limit', required: true, class: 'appWidgetInput', style: 'width: 100px', missingMessage: '<?php echo $this->translator(true)->_('config.numberOfMessagesRequired'); ?>'" />
				</div>
				
				<div class="appFormRow">
					<label class="appTopLabel" for="language_code"><?php echo $this->translator()->_('config.isoLanguageCode'); ?>:</label>
					<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'language_code', class: 'appWidgetInput', style: 'width: 100px'" />
				</div>
				
				<div class="appFormRow">
					<label class="appTopLabel"><input data-dojo-type="dijit.form.RadioButton" data-dojo-props="name: 'search_by', value: 'tag', class: 'appWidgetInput'" /> <?php echo $this->translator()->_('config.searchByTag'); ?></label>
					<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'tag', class: 'appWidgetInput', style: 'width: 98%'" />
				</div>
				
				<div class="appFormRow">
					<label class="appTopLabel"><input data-dojo-type="dijit.form.RadioButton" data-dojo-props="name: 'search_by', value: 'username', class: 'appWidgetInput'" /> <?php echo $this->translator()->_('config.searchByUser'); ?></label>
					<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'username', class: 'appWidgetInput', style: 'width: 50%'" />
				</div>
			</div>
			<!-- /Basic -->
			
			<!-- Theme -->
			<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('config.theme'); ?>', style: 'padding-top: 8px'">
				<div class="appFormRow">
					<input data-dojo-type="dijit.form.TextBox" data-dojo-props="name: 'theme', class: 'appWidgetInput'" />
				</div>
			</div>
			<!-- /Theme -->
		</div>
	</div>
</div>

<script type="text/javascript">
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.form.Select");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.layout.TabContainer");
</script>
