<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		menu
 * @subpackage	widgets
 * @since		1.0
 * @version		2012-03-17
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->script()
	 ->appendFile($this->APP_STATIC_URL . '/templates/default/js/jquery.dimensions.min.js')
	 ->appendFile($this->APP_STATIC_URL . '/templates/default/js/jquery.positionBy.min.js')
	 ->appendFile($this->APP_STATIC_URL . '/templates/default/js/jquery.bgiframe.min.js')
	 ->appendFile($this->APP_STATIC_URL . '/templates/default/js/jquery.jdMenu.min.js');
?>

<div class="menuWidgetsMenu">
	<?php
	echo $this->navigation()
			  ->menu()
			  ->renderMenu($this->container, array('ulClass' => 'jd_menu'));
	?>
</div>
